using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Cm00102
    {
        public string Chekbkid { get; set; }
        public short EftoptionalBankLine1 { get; set; }
        public short EftoptionalBankLine2 { get; set; }
        public string EftbankLineArray11 { get; set; }
        public string EftbankLineArray12 { get; set; }
        public string EftbankLineArray13 { get; set; }
        public string EftbankLineArray14 { get; set; }
        public string EftbankLineArray15 { get; set; }
        public string EftbankLineArray16 { get; set; }
        public string EftbankLineArray17 { get; set; }
        public string EftbankLineArray18 { get; set; }
        public string EftbankLineArray19 { get; set; }
        public string EftbankLineArray110 { get; set; }
        public string EftbankLineArray111 { get; set; }
        public string EftbankLineArray112 { get; set; }
        public string EftbankLineArray113 { get; set; }
        public string EftbankLineArray114 { get; set; }
        public string EftbankLineArray115 { get; set; }
        public string EftbankLineArray116 { get; set; }
        public string EftbankLineArray117 { get; set; }
        public string EftbankLineArray118 { get; set; }
        public string EftbankLineArray119 { get; set; }
        public string EftbankLineArray120 { get; set; }
        public string EftbankLineArray121 { get; set; }
        public string EftbankLineArray122 { get; set; }
        public string EftbankLineArray123 { get; set; }
        public string EftbankLineArray124 { get; set; }
        public string EftbankLineArray125 { get; set; }
        public string EftbankLineArray21 { get; set; }
        public string EftbankLineArray22 { get; set; }
        public string EftbankLineArray23 { get; set; }
        public string EftbankLineArray24 { get; set; }
        public string EftbankLineArray25 { get; set; }
        public string EftbankLineArray26 { get; set; }
        public string EftbankLineArray27 { get; set; }
        public string EftbankLineArray28 { get; set; }
        public string EftbankLineArray29 { get; set; }
        public string EftbankLineArray210 { get; set; }
        public string EftbankLineArray211 { get; set; }
        public string EftbankLineArray212 { get; set; }
        public string EftbankLineArray213 { get; set; }
        public string EftbankLineArray214 { get; set; }
        public string EftbankLineArray215 { get; set; }
        public string EftbankLineArray216 { get; set; }
        public string EftbankLineArray217 { get; set; }
        public string EftbankLineArray218 { get; set; }
        public string EftbankLineArray219 { get; set; }
        public string EftbankLineArray220 { get; set; }
        public string EftbankLineArray221 { get; set; }
        public string EftbankLineArray222 { get; set; }
        public string EftbankLineArray223 { get; set; }
        public string EftbankLineArray224 { get; set; }
        public string EftbankLineArray225 { get; set; }
        public string EftbankLineArray31 { get; set; }
        public string EftbankLineArray32 { get; set; }
        public string EftbankLineArray33 { get; set; }
        public string EftbankLineArray34 { get; set; }
        public string EftbankLineArray35 { get; set; }
        public string EftbankLineArray36 { get; set; }
        public string EftbankLineArray37 { get; set; }
        public string EftbankLineArray38 { get; set; }
        public string EftbankLineArray39 { get; set; }
        public string EftbankLineArray310 { get; set; }
        public string EftbankLineArray311 { get; set; }
        public string EftbankLineArray312 { get; set; }
        public string EftbankLineArray313 { get; set; }
        public string EftbankLineArray314 { get; set; }
        public string EftbankLineArray315 { get; set; }
        public string EftbankLineArray316 { get; set; }
        public string EftbankLineArray317 { get; set; }
        public string EftbankLineArray318 { get; set; }
        public string EftbankLineArray319 { get; set; }
        public string EftbankLineArray320 { get; set; }
        public string EftbankLineArray321 { get; set; }
        public string EftbankLineArray322 { get; set; }
        public string EftbankLineArray323 { get; set; }
        public string EftbankLineArray324 { get; set; }
        public string EftbankLineArray325 { get; set; }
        public string EftbankLineArray41 { get; set; }
        public string EftbankLineArray42 { get; set; }
        public string EftbankLineArray43 { get; set; }
        public string EftbankLineArray44 { get; set; }
        public string EftbankLineArray45 { get; set; }
        public string EftbankLineArray46 { get; set; }
        public string EftbankLineArray47 { get; set; }
        public string EftbankLineArray48 { get; set; }
        public string EftbankLineArray49 { get; set; }
        public string EftbankLineArray410 { get; set; }
        public string EftbankLineArray411 { get; set; }
        public string EftbankLineArray412 { get; set; }
        public string EftbankLineArray413 { get; set; }
        public string EftbankLineArray414 { get; set; }
        public string EftbankLineArray415 { get; set; }
        public string EftbankLineArray416 { get; set; }
        public string EftbankLineArray417 { get; set; }
        public string EftbankLineArray418 { get; set; }
        public string EftbankLineArray419 { get; set; }
        public string EftbankLineArray420 { get; set; }
        public string EftbankLineArray421 { get; set; }
        public string EftbankLineArray422 { get; set; }
        public string EftbankLineArray423 { get; set; }
        public string EftbankLineArray424 { get; set; }
        public string EftbankLineArray425 { get; set; }
        public string EftbankLineArray51 { get; set; }
        public string EftbankLineArray52 { get; set; }
        public string EftbankLineArray53 { get; set; }
        public string EftbankLineArray54 { get; set; }
        public string EftbankLineArray55 { get; set; }
        public string EftbankLineArray56 { get; set; }
        public string EftbankLineArray57 { get; set; }
        public string EftbankLineArray58 { get; set; }
        public string EftbankLineArray59 { get; set; }
        public string EftbankLineArray510 { get; set; }
        public string EftbankLineArray511 { get; set; }
        public string EftbankLineArray512 { get; set; }
        public string EftbankLineArray513 { get; set; }
        public string EftbankLineArray514 { get; set; }
        public string EftbankLineArray515 { get; set; }
        public string EftbankLineArray516 { get; set; }
        public string EftbankLineArray517 { get; set; }
        public string EftbankLineArray518 { get; set; }
        public string EftbankLineArray519 { get; set; }
        public string EftbankLineArray520 { get; set; }
        public string EftbankLineArray521 { get; set; }
        public string EftbankLineArray522 { get; set; }
        public string EftbankLineArray523 { get; set; }
        public string EftbankLineArray524 { get; set; }
        public string EftbankLineArray525 { get; set; }
        public string EftbankLineArray61 { get; set; }
        public string EftbankLineArray62 { get; set; }
        public string EftbankLineArray63 { get; set; }
        public string EftbankLineArray64 { get; set; }
        public string EftbankLineArray65 { get; set; }
        public string EftbankLineArray66 { get; set; }
        public string EftbankLineArray67 { get; set; }
        public string EftbankLineArray68 { get; set; }
        public string EftbankLineArray69 { get; set; }
        public string EftbankLineArray610 { get; set; }
        public string EftbankLineArray611 { get; set; }
        public string EftbankLineArray612 { get; set; }
        public string EftbankLineArray613 { get; set; }
        public string EftbankLineArray614 { get; set; }
        public string EftbankLineArray615 { get; set; }
        public string EftbankLineArray616 { get; set; }
        public string EftbankLineArray617 { get; set; }
        public string EftbankLineArray618 { get; set; }
        public string EftbankLineArray619 { get; set; }
        public string EftbankLineArray620 { get; set; }
        public string EftbankLineArray621 { get; set; }
        public string EftbankLineArray622 { get; set; }
        public string EftbankLineArray623 { get; set; }
        public string EftbankLineArray624 { get; set; }
        public string EftbankLineArray625 { get; set; }
        public string EftbankLineArray71 { get; set; }
        public string EftbankLineArray72 { get; set; }
        public string EftbankLineArray73 { get; set; }
        public string EftbankLineArray74 { get; set; }
        public string EftbankLineArray75 { get; set; }
        public string EftbankLineArray76 { get; set; }
        public string EftbankLineArray77 { get; set; }
        public string EftbankLineArray78 { get; set; }
        public string EftbankLineArray79 { get; set; }
        public string EftbankLineArray710 { get; set; }
        public string EftbankLineArray711 { get; set; }
        public string EftbankLineArray712 { get; set; }
        public string EftbankLineArray713 { get; set; }
        public string EftbankLineArray714 { get; set; }
        public string EftbankLineArray715 { get; set; }
        public string EftbankLineArray716 { get; set; }
        public string EftbankLineArray717 { get; set; }
        public string EftbankLineArray718 { get; set; }
        public string EftbankLineArray719 { get; set; }
        public string EftbankLineArray720 { get; set; }
        public string EftbankLineArray721 { get; set; }
        public string EftbankLineArray722 { get; set; }
        public string EftbankLineArray723 { get; set; }
        public string EftbankLineArray724 { get; set; }
        public string EftbankLineArray725 { get; set; }
        public string EftbankLineArray81 { get; set; }
        public string EftbankLineArray82 { get; set; }
        public string EftbankLineArray83 { get; set; }
        public string EftbankLineArray84 { get; set; }
        public string EftbankLineArray85 { get; set; }
        public string EftbankLineArray86 { get; set; }
        public string EftbankLineArray87 { get; set; }
        public string EftbankLineArray88 { get; set; }
        public string EftbankLineArray89 { get; set; }
        public string EftbankLineArray810 { get; set; }
        public string EftbankLineArray811 { get; set; }
        public string EftbankLineArray812 { get; set; }
        public string EftbankLineArray813 { get; set; }
        public string EftbankLineArray814 { get; set; }
        public string EftbankLineArray815 { get; set; }
        public string EftbankLineArray816 { get; set; }
        public string EftbankLineArray817 { get; set; }
        public string EftbankLineArray818 { get; set; }
        public string EftbankLineArray819 { get; set; }
        public string EftbankLineArray820 { get; set; }
        public string EftbankLineArray821 { get; set; }
        public string EftbankLineArray822 { get; set; }
        public string EftbankLineArray823 { get; set; }
        public string EftbankLineArray824 { get; set; }
        public string EftbankLineArray825 { get; set; }
        public int DexRowId { get; set; }
    }
}
