using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Iv70500
    {
        public short Prtbysit { get; set; }
        public short Prntoptn { get; set; }
        public string Sttgndsc { get; set; }
        public string Engendsc { get; set; }
        public string Enusrcat1 { get; set; }
        public string Enusrcat2 { get; set; }
        public string Enusrcat3 { get; set; }
        public string Enusrcat4 { get; set; }
        public string Enusrcat5 { get; set; }
        public string Enusrcat6 { get; set; }
        public short Kitsrtby { get; set; }
        public string Strtucat1 { get; set; }
        public string Strtucat2 { get; set; }
        public string Strtucat3 { get; set; }
        public string Strtucat4 { get; set; }
        public string Strtucat5 { get; set; }
        public string Strtucat6 { get; set; }
        public string Sttitnum { get; set; }
        public string Enitmnbr { get; set; }
        public short Prvdrinf { get; set; }
        public byte Prtdscnt { get; set; }
        public string Finrptnm { get; set; }
        public byte Prntnots { get; set; }
        public short Prnttype { get; set; }
        public byte Askechtm { get; set; }
        public byte Inclgnds { get; set; }
        public byte Prntofil { get; set; }
        public byte Prtoprtr { get; set; }
        public byte Prtoscrn { get; set; }
        public short Iffilxst { get; set; }
        public string Filexpnm { get; set; }
        public short Expttype { get; set; }
        public short Rptgrind { get; set; }
        public string Sttclass { get; set; }
        public string Endclass { get; set; }
        public string Sttsched { get; set; }
        public string Enschdul { get; set; }
        public string Sttloccd { get; set; }
        public string Enlocncd { get; set; }
        public string Sttlotty { get; set; }
        public string Enlottyp { get; set; }
        public DateTime Strtngdt { get; set; }
        public DateTime Endingdt { get; set; }
        public short Endtkndt { get; set; }
        public short Sttokndt { get; set; }
        public string Strctnum { get; set; }
        public string Enrctnbr { get; set; }
        public short Rtpachin { get; set; }
        public decimal Rtgrsbin { get; set; }
        public short Sortby { get; set; }
        public byte Prtsrlot { get; set; }
        public byte Inzroqty { get; set; }
        public byte Prtitqty { get; set; }
        public string Sttbinum { get; set; }
        public string Enbinnbr { get; set; }
        public string Stdocnum { get; set; }
        public string Endocnum { get; set; }
        public short Stdoctyp { get; set; }
        public short Endoctyp { get; set; }
        public string Sttmodul { get; set; }
        public string Endmodul { get; set; }
        public string Strxsrc { get; set; }
        public string Entrxsrc { get; set; }
        public string Stbchsrc { get; set; }
        public string Enbchsrc { get; set; }
        public string Stbchnum { get; set; }
        public string Endbnmbr { get; set; }
        public string Stvndrid { get; set; }
        public string Endvndid { get; set; }
        public byte Inqtyreq { get; set; }
        public byte Inzrorlv { get; set; }
        public short Calsgqty { get; set; }
        public short Rcptopts { get; set; }
        public short Vendropt { get; set; }
        public short Segsrtby { get; set; }
        public string Sttacnum1 { get; set; }
        public string Sttacnum2 { get; set; }
        public string Sttacnum3 { get; set; }
        public string Sttacnum4 { get; set; }
        public string Sttacnum5 { get; set; }
        public string Eaccnbr1 { get; set; }
        public string Eaccnbr2 { get; set; }
        public string Eaccnbr3 { get; set; }
        public string Eaccnbr4 { get; set; }
        public string Eaccnbr5 { get; set; }
        public short Segmntrg { get; set; }
        public string StartPriceLevel { get; set; }
        public string EndPriceLevel { get; set; }
        public short StartQtyType { get; set; }
        public short EndQtyType { get; set; }
        public string StartComponentItemNum { get; set; }
        public string EndComponentItemNumbe { get; set; }
        public byte BmAssemblyJournal { get; set; }
        public byte BmDistributionDetail { get; set; }
        public byte BmBillStatusActive { get; set; }
        public byte BmBillStatusPending { get; set; }
        public byte BmBillStatusObsolete { get; set; }
        public byte BmCompStatusActive { get; set; }
        public byte BmCompStatusPending { get; set; }
        public byte BmCompStatusObsolete { get; set; }
        public byte BmCompTypeMiscCharge { get; set; }
        public byte BmCompTypeServices { get; set; }
        public byte BmCompTypeFlatFee { get; set; }
        public byte BmPrintNotesBill { get; set; }
        public byte BmPrintNotesComp { get; set; }
        public short BmPrintCostOptions { get; set; }
        public short MaxLevels { get; set; }
        public DateTime Date1 { get; set; }
        public byte Bmtrxstatnotrel { get; set; }
        public byte Bmtrxstatrel { get; set; }
        public short Options { get; set; }
        public string StartTrxId { get; set; }
        public string EndTrxId { get; set; }
        public DateTime StartingTrxDate { get; set; }
        public DateTime EndingTrxDate { get; set; }
        public string Strtsrlt { get; set; }
        public string Endserlt { get; set; }
        public string StartPriceGroup { get; set; }
        public string EndPriceGroup { get; set; }
        public string Stcurrid { get; set; }
        public string Endcurid { get; set; }
        public short Strtabccd { get; set; }
        public short Endabccd { get; set; }
        public string Strtstckcntid { get; set; }
        public string Endstckcntid { get; set; }
        public string StartLandedCostId { get; set; }
        public string EndLandedCostId { get; set; }
        public string StartLandedCostGroupId { get; set; }
        public string EndLandedCostGroupId { get; set; }
        public DateTime Asofdate { get; set; }
        public byte Inzrqtyi { get; set; }
        public string Startbin { get; set; }
        public string Endbin { get; set; }
        public string Lngstrtdesc { get; set; }
        public string Lngenddesc { get; set; }
        public byte Useglpostingdate { get; set; }
        public byte Inngvqty { get; set; }
        public short Costavgperiodic { get; set; }
        public byte Prtinact { get; set; }
        public int DexRowId { get; set; }
    }
}
