using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Ivc30101
    {
        public short Doctype { get; set; }
        public string Invcnmbr { get; set; }
        public string Bachnumb { get; set; }
        public string Bchsourc { get; set; }
        public string Pckslpno { get; set; }
        public string Custnmbr { get; set; }
        public string Custname { get; set; }
        public string Cstponbr { get; set; }
        public DateTime Postdate { get; set; }
        public DateTime Glpostdt { get; set; }
        public DateTime Docdate { get; set; }
        public DateTime Quotedat { get; set; }
        public DateTime Ordrdate { get; set; }
        public DateTime Discdate { get; set; }
        public DateTime Duedate { get; set; }
        public byte Holdnt { get; set; }
        public string Shipmthd { get; set; }
        public string Taxexmt1 { get; set; }
        public string Taxexmt2 { get; set; }
        public string Taxschid { get; set; }
        public string Frtschid { get; set; }
        public short Frgttxbl { get; set; }
        public decimal Frttxamt { get; set; }
        public string Mscschid { get; set; }
        public short Misctxbl { get; set; }
        public decimal Msctxamt { get; set; }
        public decimal Mrkdnamt { get; set; }
        public string Slprsnid { get; set; }
        public string Salsterr { get; set; }
        public string Txrgnnum { get; set; }
        public string Pymtrmid { get; set; }
        public string Prclevel { get; set; }
        public string Locncode { get; set; }
        public string Curncyid { get; set; }
        public string Commntid { get; set; }
        public decimal Docamnt { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Frtamnt { get; set; }
        public decimal Miscamnt { get; set; }
        public decimal Taxamnt { get; set; }
        public decimal Txbtxamt { get; set; }
        public decimal Trdisamt { get; set; }
        public decimal Acctamnt { get; set; }
        public decimal Pymtrcvd { get; set; }
        public decimal Codamnt { get; set; }
        public decimal Extdcost { get; set; }
        public decimal Disavtkn { get; set; }
        public decimal Discrtnd { get; set; }
        public decimal Distknam { get; set; }
        public decimal Disavamt { get; set; }
        public decimal Dscdlram { get; set; }
        public short Dscpctam { get; set; }
        public string Prbtadcd { get; set; }
        public string Prstadcd { get; set; }
        public string Cntcprsn { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Ccode { get; set; }
        public string Country { get; set; }
        public string Phnumbr1 { get; set; }
        public string Phnumbr2 { get; set; }
        public string Phone3 { get; set; }
        public string Faxnumbr { get; set; }
        public short Comappto { get; set; }
        public decimal Comdlram { get; set; }
        public decimal Ncomamnt { get; set; }
        public string Upszone { get; set; }
        public string Lstusred { get; set; }
        public DateTime Lstedtdt { get; set; }
        public DateTime Modifdt { get; set; }
        public DateTime Creatddt { get; set; }
        public string User2ent { get; set; }
        public decimal Noteindx { get; set; }
        public short Timesprt { get; set; }
        public short Nocartns { get; set; }
        public string Userdef1 { get; set; }
        public string Userdef2 { get; set; }
        public short Voidstts { get; set; }
        public string Trxsorce { get; set; }
        public int Lnitmseq { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string Comment4 { get; set; }
        public byte Ectrx { get; set; }
        public string ShipToName { get; set; }
        public DateTime TaxDate { get; set; }
        public byte Aplywith { get; set; }
        public decimal Withhamt { get; set; }
        public int DexRowId { get; set; }
        public string Cmmttext { get; set; }
    }
}
