using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Pop30100
    {
        public string Ponumber { get; set; }
        public short Postatus { get; set; }
        public short Statgrp { get; set; }
        public short Potype { get; set; }
        public string User2ent { get; set; }
        public string Confirm1 { get; set; }
        public DateTime Docdate { get; set; }
        public DateTime Lstedtdt { get; set; }
        public DateTime Lstprtdt { get; set; }
        public DateTime Prmdate { get; set; }
        public DateTime Prmshpdte { get; set; }
        public DateTime Reqdate { get; set; }
        public DateTime Reqtndt { get; set; }
        public string Shipmthd { get; set; }
        public string Txrgnnum { get; set; }
        public decimal Remsubto { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Trdisamt { get; set; }
        public decimal Trdpctpr { get; set; }
        public decimal Frtamnt { get; set; }
        public decimal Mscchamt { get; set; }
        public decimal Taxamnt { get; set; }
        public string Vendorid { get; set; }
        public string Vendname { get; set; }
        public decimal Minorder { get; set; }
        public string Vadcdpad { get; set; }
        public short Cmpanyid { get; set; }
        public string Prbtadcd { get; set; }
        public string Prstadcd { get; set; }
        public string Cmpnynam { get; set; }
        public string Contact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Ccode { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Fax { get; set; }
        public string Pymtrmid { get; set; }
        public decimal Dscdlram { get; set; }
        public short Dscpctam { get; set; }
        public decimal Disamtav { get; set; }
        public DateTime Discdate { get; set; }
        public DateTime Duedate { get; set; }
        public string Custnmbr { get; set; }
        public short Timesprt { get; set; }
        public DateTime Creatddt { get; set; }
        public DateTime Modifdt { get; set; }
        public decimal Ponotids1 { get; set; }
        public decimal Ponotids2 { get; set; }
        public decimal Ponotids3 { get; set; }
        public decimal Ponotids4 { get; set; }
        public decimal Ponotids5 { get; set; }
        public decimal Ponotids6 { get; set; }
        public decimal Ponotids7 { get; set; }
        public decimal Ponotids8 { get; set; }
        public decimal Ponotids9 { get; set; }
        public decimal Ponotids10 { get; set; }
        public decimal Ponotids11 { get; set; }
        public decimal Ponotids12 { get; set; }
        public decimal Ponotids13 { get; set; }
        public decimal Ponotids14 { get; set; }
        public decimal Ponotids15 { get; set; }
        public string Trxsorce { get; set; }
        public string Commntid { get; set; }
        public decimal Cancsub { get; set; }
        public string Curncyid { get; set; }
        public short Currnidx { get; set; }
        public string Ratetpid { get; set; }
        public string Exgtblid { get; set; }
        public decimal Xchgrate { get; set; }
        public DateTime Exchdate { get; set; }
        public DateTime Time1 { get; set; }
        public short Ratecalc { get; set; }
        public decimal Denxrate { get; set; }
        public short Mctrxstt { get; set; }
        public decimal Oremsubt { get; set; }
        public decimal Orsubtot { get; set; }
        public decimal OriginatingCanceledSub { get; set; }
        public decimal Ortdisam { get; set; }
        public decimal Orfrtamt { get; set; }
        public decimal Omiscamt { get; set; }
        public decimal Ortaxamt { get; set; }
        public decimal Orddlrat { get; set; }
        public decimal Odisamtav { get; set; }
        public string Buyerid { get; set; }
        public byte Allowsocmts { get; set; }
        public short Disgrper { get; set; }
        public short Duegrper { get; set; }
        public short RevisionNumber { get; set; }
        public string Taxschid { get; set; }
        public short Txschsrc { get; set; }
        public byte Bsivcttl { get; set; }
        public short PurchaseFreightTaxable { get; set; }
        public short PurchaseMiscTaxable { get; set; }
        public string Frtschid { get; set; }
        public string Mscschid { get; set; }
        public decimal Frttxamt { get; set; }
        public decimal Orfrttax { get; set; }
        public decimal Msctxamt { get; set; }
        public decimal Ormsctax { get; set; }
        public decimal Bcktxamt { get; set; }
        public decimal Obtaxamt { get; set; }
        public decimal BackoutFreightTaxAmt { get; set; }
        public decimal OrigBackoutFreightTaxAmt { get; set; }
        public decimal BackoutMiscTaxAmt { get; set; }
        public decimal OrigBackoutMiscTaxAmt { get; set; }
        public short Flags { get; set; }
        public string Popcontnum { get; set; }
        public DateTime Contenddte { get; set; }
        public short Cntrlblktby { get; set; }
        public string Purchcmpnynam { get; set; }
        public string Purchcontact { get; set; }
        public string Purchaddress1 { get; set; }
        public string Purchaddress2 { get; set; }
        public string Purchaddress3 { get; set; }
        public string Purchcity { get; set; }
        public string Purchstate { get; set; }
        public string Purchzipcode { get; set; }
        public string Purchccode { get; set; }
        public string Purchcountry { get; set; }
        public string Purchphone1 { get; set; }
        public string Purchphone2 { get; set; }
        public string Purchphone3 { get; set; }
        public string Purchfax { get; set; }
        public decimal Blnktlineextqtysum { get; set; }
        public short WorkflowApprovalStatus { get; set; }
        public short WorkflowPriority { get; set; }
        public short WorkflowStatus { get; set; }
        public short PrintPhoneNumberGb { get; set; }
        public decimal PrepaymentAmount { get; set; }
        public decimal OriginatingPrepaymentAmt { get; set; }
        public DateTime DexRowTs { get; set; }
        public int DexRowId { get; set; }
    }
}
