using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Pop40100
    {
        public short Index1 { get; set; }
        public string PoCode { get; set; }
        public string Ponumber { get; set; }
        public short Poformat { get; set; }
        public string Poprctnm { get; set; }
        public string ReceiptCode { get; set; }
        public short Decplqty { get; set; }
        public short Decplcur { get; set; }
        public byte Pohist { get; set; }
        public byte Rcpthist { get; set; }
        public byte Disthist { get; set; }
        public short Dsplyitm { get; set; }
        public DateTime Creatddt { get; set; }
        public DateTime Modifdt { get; set; }
        public short NumberOfLines { get; set; }
        public byte Popalwop1 { get; set; }
        public byte Popalwop2 { get; set; }
        public byte Popalwop3 { get; set; }
        public byte Popalwop4 { get; set; }
        public byte Popalwop5 { get; set; }
        public string Poppswrd1 { get; set; }
        public string Poppswrd2 { get; set; }
        public string Poppswrd3 { get; set; }
        public string Poppswrd4 { get; set; }
        public string Poppswrd5 { get; set; }
        public short Defaultsitemethod { get; set; }
        public byte Allowholdedit { get; set; }
        public byte Autohold { get; set; }
        public byte SearchPoqtysFromSo { get; set; }
        public byte TransferLineComments { get; set; }
        public short PurchaseNonIvTaxable { get; set; }
        public short PurchaseFreightTaxable { get; set; }
        public short PurchaseMiscTaxable { get; set; }
        public string Nonivsch { get; set; }
        public string Frtschid { get; set; }
        public string Mscschid { get; set; }
        public short Useadvtx { get; set; }
        public string Taxschid { get; set; }
        public string UserDefinedPrompt01 { get; set; }
        public string UserDefinedPrompt02 { get; set; }
        public string UserDefinedPrompt03 { get; set; }
        public string UserDefinedPrompt04 { get; set; }
        public string UserDefinedPrompt05 { get; set; }
        public string UserDefinedPrompt06 { get; set; }
        public string UserDefinedPrompt07 { get; set; }
        public string UserDefinedPrompt08 { get; set; }
        public string UserDefinedPrompt09 { get; set; }
        public string UserDefinedPrompt10 { get; set; }
        public string UserDefinedPrompt11 { get; set; }
        public string UserDefinedPrompt12 { get; set; }
        public string UserDefinedPrompt13 { get; set; }
        public string UserDefinedPrompt14 { get; set; }
        public string UserDefinedPrompt15 { get; set; }
        public string UserDefinedPrompt16 { get; set; }
        public string UserDefinedPrompt17 { get; set; }
        public string UserDefinedPrompt18 { get; set; }
        public string UserDefinedPrompt19 { get; set; }
        public string UserDefinedPrompt20 { get; set; }
        public string UserDefinedPrompt21 { get; set; }
        public string UserDefinedPrompt22 { get; set; }
        public string UserDefinedPrompt23 { get; set; }
        public string UserDefinedPrompt24 { get; set; }
        public string UserDefinedPrompt25 { get; set; }
        public string UserDefinedPrompt26 { get; set; }
        public string UserDefinedPrompt27 { get; set; }
        public string UserDefinedPrompt28 { get; set; }
        public string UserDefinedPrompt29 { get; set; }
        public string UserDefinedPrompt30 { get; set; }
        public string UserDefinedPrompt31 { get; set; }
        public string UserDefinedPrompt32 { get; set; }
        public string UserDefinedPrompt33 { get; set; }
        public string UserDefinedPrompt34 { get; set; }
        public string UserDefinedPrompt35 { get; set; }
        public decimal FreightTaxSchedNoteIdx { get; set; }
        public decimal MiscTaxSchedNoteIdx { get; set; }
        public decimal NonIvtaxSchedNoteIdx { get; set; }
        public decimal SingleTaxSchedNoteIdx { get; set; }
        public short ReplenishmentLevel { get; set; }
        public short PoporderMethod { get; set; }
        public string MasterLocationCode { get; set; }
        public short PopvendorSelection { get; set; }
        public short PoppricingSelection { get; set; }
        public byte IncludeAllocations { get; set; }
        public byte IncludeBackorders { get; set; }
        public byte IncludeRequisitions { get; set; }
        public byte Retorigtax { get; set; }
        public byte Onepoperaddr { get; set; }
        public byte Calcreldt { get; set; }
        public short DefaultDocumentDate { get; set; }
        public byte UseQtyOverageTolerance { get; set; }
        public byte UseQtyShortageTolerance { get; set; }
        public int QtyOverTolerancePercent { get; set; }
        public int QtyShortTolerancePercent { get; set; }
        public byte AllowPoprepayments { get; set; }
        public byte CreateManualPrepayment { get; set; }
        public string PrepaymentPassword { get; set; }
        public int PrepaymentAccountIndex { get; set; }
        public string RequisitionCode { get; set; }
        public string PoprequisitionNumber { get; set; }
        public byte RequisitionMaintainHist { get; set; }
        public short RequisitionDefDocDate { get; set; }
        public short RequisitionDefSiteMethod { get; set; }
        public short RequisitionVendorSelect { get; set; }
        public short RequisitionCostSelection { get; set; }
        public byte ReqCreateOnePoperAddress { get; set; }
        public byte ReqTransferLineComments { get; set; }
        public byte SearchPoqtysFromRequisit { get; set; }
        public string ReqHdrUdPrompt1 { get; set; }
        public string ReqHdrUdPrompt2 { get; set; }
        public string ReqLineUdPrompt1 { get; set; }
        public string ReqLineUdPrompt2 { get; set; }
        public int DexRowId { get; set; }
    }
}
