using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Upr10214
    {
        public string Employid { get; set; }
        public decimal Pyytdarr1 { get; set; }
        public decimal Pyytdarr2 { get; set; }
        public decimal Pyytdarr3 { get; set; }
        public decimal Pyytdarr4 { get; set; }
        public decimal Pyytdarr5 { get; set; }
        public decimal Pyytdarr6 { get; set; }
        public decimal Pyytdarr7 { get; set; }
        public decimal Pyytdarr8 { get; set; }
        public decimal Pyytdarr9 { get; set; }
        public decimal Pyytdarr10 { get; set; }
        public decimal Pyytdarr11 { get; set; }
        public decimal Pyytdarr12 { get; set; }
        public decimal Pyytdarr13 { get; set; }
        public decimal Pyytdarr14 { get; set; }
        public decimal Pyytdarr15 { get; set; }
        public decimal Pyytdarr16 { get; set; }
        public decimal Pyytdarr17 { get; set; }
        public decimal Pyytdarr18 { get; set; }
        public decimal Pyytdarr19 { get; set; }
        public decimal Pyytdarr20 { get; set; }
        public decimal Pyytdarr21 { get; set; }
        public decimal Pyytdarr22 { get; set; }
        public decimal Pyytdarr23 { get; set; }
        public decimal Pyytdarr24 { get; set; }
        public decimal Pyytdarr25 { get; set; }
        public decimal Damytdar1 { get; set; }
        public decimal Damytdar2 { get; set; }
        public decimal Damytdar3 { get; set; }
        public decimal Damytdar4 { get; set; }
        public decimal Damytdar5 { get; set; }
        public decimal Damytdar6 { get; set; }
        public decimal Damytdar7 { get; set; }
        public decimal Damytdar8 { get; set; }
        public decimal Damytdar9 { get; set; }
        public decimal Damytdar10 { get; set; }
        public decimal Damytdar11 { get; set; }
        public decimal Damytdar12 { get; set; }
        public decimal Damytdar13 { get; set; }
        public decimal Damytdar14 { get; set; }
        public decimal Damytdar15 { get; set; }
        public decimal Damytdar16 { get; set; }
        public decimal Damytdar17 { get; set; }
        public decimal Damytdar18 { get; set; }
        public decimal Damytdar19 { get; set; }
        public decimal Damytdar20 { get; set; }
        public decimal Damytdar21 { get; set; }
        public decimal Damytdar22 { get; set; }
        public decimal Damytdar23 { get; set; }
        public decimal Damytdar24 { get; set; }
        public decimal Damytdar25 { get; set; }
        public decimal Bamytdar1 { get; set; }
        public decimal Bamytdar2 { get; set; }
        public decimal Bamytdar3 { get; set; }
        public decimal Bamytdar4 { get; set; }
        public decimal Bamytdar5 { get; set; }
        public decimal Bamytdar6 { get; set; }
        public decimal Bamytdar7 { get; set; }
        public decimal Bamytdar8 { get; set; }
        public decimal Bamytdar9 { get; set; }
        public decimal Bamytdar10 { get; set; }
        public decimal Bamytdar11 { get; set; }
        public decimal Bamytdar12 { get; set; }
        public decimal Bamytdar13 { get; set; }
        public decimal Bamytdar14 { get; set; }
        public decimal Bamytdar15 { get; set; }
        public decimal Bamytdar16 { get; set; }
        public decimal Bamytdar17 { get; set; }
        public decimal Bamytdar18 { get; set; }
        public decimal Bamytdar19 { get; set; }
        public decimal Bamytdar20 { get; set; }
        public decimal Bamytdar21 { get; set; }
        public decimal Bamytdar22 { get; set; }
        public decimal Bamytdar23 { get; set; }
        public decimal Bamytdar24 { get; set; }
        public decimal Bamytdar25 { get; set; }
        public decimal Statxytd1 { get; set; }
        public decimal Statxytd2 { get; set; }
        public decimal Statxytd3 { get; set; }
        public decimal Statxytd4 { get; set; }
        public decimal Statxytd5 { get; set; }
        public decimal Statxytd6 { get; set; }
        public decimal Statxytd7 { get; set; }
        public decimal Statxytd8 { get; set; }
        public decimal Statxytd9 { get; set; }
        public decimal Statxytd10 { get; set; }
        public decimal Statxytd11 { get; set; }
        public decimal Statxytd12 { get; set; }
        public decimal Statxytd13 { get; set; }
        public decimal Statxytd14 { get; set; }
        public decimal Statxytd15 { get; set; }
        public decimal Statxytd16 { get; set; }
        public decimal Statxytd17 { get; set; }
        public decimal Statxytd18 { get; set; }
        public decimal Statxytd19 { get; set; }
        public decimal Statxytd20 { get; set; }
        public decimal Statxytd21 { get; set; }
        public decimal Statxytd22 { get; set; }
        public decimal Statxytd23 { get; set; }
        public decimal Statxytd24 { get; set; }
        public decimal Statxytd25 { get; set; }
        public decimal Lcltxytd1 { get; set; }
        public decimal Lcltxytd2 { get; set; }
        public decimal Lcltxytd3 { get; set; }
        public decimal Lcltxytd4 { get; set; }
        public decimal Lcltxytd5 { get; set; }
        public decimal Lcltxytd6 { get; set; }
        public decimal Lcltxytd7 { get; set; }
        public decimal Lcltxytd8 { get; set; }
        public decimal Lcltxytd9 { get; set; }
        public decimal Lcltxytd10 { get; set; }
        public decimal Lcltxytd11 { get; set; }
        public decimal Lcltxytd12 { get; set; }
        public decimal Lcltxytd13 { get; set; }
        public decimal Lcltxytd14 { get; set; }
        public decimal Lcltxytd15 { get; set; }
        public decimal Lcltxytd16 { get; set; }
        public decimal Lcltxytd17 { get; set; }
        public decimal Lcltxytd18 { get; set; }
        public decimal Lcltxytd19 { get; set; }
        public decimal Lcltxytd20 { get; set; }
        public decimal Lcltxytd21 { get; set; }
        public decimal Lcltxytd22 { get; set; }
        public decimal Lcltxytd23 { get; set; }
        public decimal Lcltxytd24 { get; set; }
        public decimal Lcltxytd25 { get; set; }
        public decimal Grswgytd { get; set; }
        public decimal Ntwgsytd { get; set; }
        public decimal Ficawytd { get; set; }
        public decimal Fcassytd { get; set; }
        public decimal Ficamytd { get; set; }
        public decimal Fdwdgytd { get; set; }
        public decimal Swhdgytd { get; set; }
        public decimal Lcwhgytd { get; set; }
        public string Userid { get; set; }
        public decimal Pyfytdarr1 { get; set; }
        public decimal Pyfytdarr2 { get; set; }
        public decimal Pyfytdarr3 { get; set; }
        public decimal Pyfytdarr4 { get; set; }
        public decimal Pyfytdarr5 { get; set; }
        public decimal Pyfytdarr6 { get; set; }
        public decimal Pyfytdarr7 { get; set; }
        public decimal Pyfytdarr8 { get; set; }
        public decimal Pyfytdarr9 { get; set; }
        public decimal Pyfytdarr10 { get; set; }
        public decimal Pyfytdarr11 { get; set; }
        public decimal Pyfytdarr12 { get; set; }
        public decimal Pyfytdarr13 { get; set; }
        public decimal Pyfytdarr14 { get; set; }
        public decimal Pyfytdarr15 { get; set; }
        public decimal Pyfytdarr16 { get; set; }
        public decimal Pyfytdarr17 { get; set; }
        public decimal Pyfytdarr18 { get; set; }
        public decimal Pyfytdarr19 { get; set; }
        public decimal Pyfytdarr20 { get; set; }
        public decimal Pyfytdarr21 { get; set; }
        public decimal Pyfytdarr22 { get; set; }
        public decimal Pyfytdarr23 { get; set; }
        public decimal Pyfytdarr24 { get; set; }
        public decimal Pyfytdarr25 { get; set; }
        public decimal Damfytdar1 { get; set; }
        public decimal Damfytdar2 { get; set; }
        public decimal Damfytdar3 { get; set; }
        public decimal Damfytdar4 { get; set; }
        public decimal Damfytdar5 { get; set; }
        public decimal Damfytdar6 { get; set; }
        public decimal Damfytdar7 { get; set; }
        public decimal Damfytdar8 { get; set; }
        public decimal Damfytdar9 { get; set; }
        public decimal Damfytdar10 { get; set; }
        public decimal Damfytdar11 { get; set; }
        public decimal Damfytdar12 { get; set; }
        public decimal Damfytdar13 { get; set; }
        public decimal Damfytdar14 { get; set; }
        public decimal Damfytdar15 { get; set; }
        public decimal Damfytdar16 { get; set; }
        public decimal Damfytdar17 { get; set; }
        public decimal Damfytdar18 { get; set; }
        public decimal Damfytdar19 { get; set; }
        public decimal Damfytdar20 { get; set; }
        public decimal Damfytdar21 { get; set; }
        public decimal Damfytdar22 { get; set; }
        public decimal Damfytdar23 { get; set; }
        public decimal Damfytdar24 { get; set; }
        public decimal Damfytdar25 { get; set; }
        public decimal Bamfytdar1 { get; set; }
        public decimal Bamfytdar2 { get; set; }
        public decimal Bamfytdar3 { get; set; }
        public decimal Bamfytdar4 { get; set; }
        public decimal Bamfytdar5 { get; set; }
        public decimal Bamfytdar6 { get; set; }
        public decimal Bamfytdar7 { get; set; }
        public decimal Bamfytdar8 { get; set; }
        public decimal Bamfytdar9 { get; set; }
        public decimal Bamfytdar10 { get; set; }
        public decimal Bamfytdar11 { get; set; }
        public decimal Bamfytdar12 { get; set; }
        public decimal Bamfytdar13 { get; set; }
        public decimal Bamfytdar14 { get; set; }
        public decimal Bamfytdar15 { get; set; }
        public decimal Bamfytdar16 { get; set; }
        public decimal Bamfytdar17 { get; set; }
        public decimal Bamfytdar18 { get; set; }
        public decimal Bamfytdar19 { get; set; }
        public decimal Bamfytdar20 { get; set; }
        public decimal Bamfytdar21 { get; set; }
        public decimal Bamfytdar22 { get; set; }
        public decimal Bamfytdar23 { get; set; }
        public decimal Bamfytdar24 { get; set; }
        public decimal Bamfytdar25 { get; set; }
        public int DexRowId { get; set; }
    }
}
