using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class EConnectOutSetup
    {
        public string Queuepath { get; set; }
        public int QueueEnabled { get; set; }
        public string Doctype { get; set; }
        public int InsertEnabled { get; set; }
        public int UpdateEnabled { get; set; }
        public int DeleteEnabled { get; set; }
        public string Tablename { get; set; }
        public string Alias { get; set; }
        public int Main { get; set; }
        public int Parentlevel { get; set; }
        public int Orderby { get; set; }
        public string Userdef1 { get; set; }
        public string Userdef2 { get; set; }
        public string Userdef3 { get; set; }
        public string Userdef4 { get; set; }
        public string Userdef5 { get; set; }
        public string Required1 { get; set; }
        public string Index1 { get; set; }
        public string Index2 { get; set; }
        public string Index3 { get; set; }
        public string Index4 { get; set; }
        public string Index5 { get; set; }
        public string Index6 { get; set; }
        public string Index7 { get; set; }
        public string Index8 { get; set; }
        public string Index9 { get; set; }
        public string Index10 { get; set; }
        public string Index11 { get; set; }
        public string Index12 { get; set; }
        public string Index13 { get; set; }
        public string Index14 { get; set; }
        public string Index15 { get; set; }
        public int Indexcnt { get; set; }
        public string Trigger1 { get; set; }
        public string Trigger2 { get; set; }
        public string Trigger3 { get; set; }
        public string Trigger4 { get; set; }
        public string Trigger5 { get; set; }
        public string Trigger6 { get; set; }
        public string Trigger7 { get; set; }
        public string Trigger8 { get; set; }
        public string Trigger9 { get; set; }
        public string Trigger10 { get; set; }
        public string Trigger11 { get; set; }
        public string Trigger12 { get; set; }
        public string Trigger13 { get; set; }
        public string Trigger14 { get; set; }
        public string Trigger15 { get; set; }
        public int Triggercnt { get; set; }
        public string Jointable { get; set; }
        public string Join1 { get; set; }
        public string Join2 { get; set; }
        public string Join3 { get; set; }
        public string Join4 { get; set; }
        public string Join5 { get; set; }
        public string Join6 { get; set; }
        public string Join7 { get; set; }
        public string Join8 { get; set; }
        public string Join9 { get; set; }
        public string Join10 { get; set; }
        public string Jointo1 { get; set; }
        public string Jointo2 { get; set; }
        public string Jointo3 { get; set; }
        public string Jointo4 { get; set; }
        public string Jointo5 { get; set; }
        public string Jointo6 { get; set; }
        public string Jointo7 { get; set; }
        public string Jointo8 { get; set; }
        public string Jointo9 { get; set; }
        public string Jointo10 { get; set; }
        public int Datacnt { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Data4 { get; set; }
        public string Data5 { get; set; }
        public string Data6 { get; set; }
        public string Data7 { get; set; }
        public string Data8 { get; set; }
        public string Data9 { get; set; }
        public string Data10 { get; set; }
        public string Data11 { get; set; }
        public string Data12 { get; set; }
        public string Data13 { get; set; }
        public string Data14 { get; set; }
        public string Data15 { get; set; }
        public string Data16 { get; set; }
        public string Data17 { get; set; }
        public string Data18 { get; set; }
        public string Data19 { get; set; }
        public string Data20 { get; set; }
        public string Data21 { get; set; }
        public string Data22 { get; set; }
        public string Data23 { get; set; }
        public string Data24 { get; set; }
        public string Data25 { get; set; }
        public string Data26 { get; set; }
        public string Data27 { get; set; }
        public string Data28 { get; set; }
        public string Data29 { get; set; }
        public string Data30 { get; set; }
        public string Data31 { get; set; }
        public string Data32 { get; set; }
        public string Data33 { get; set; }
        public string Data34 { get; set; }
        public string Data35 { get; set; }
        public string Data36 { get; set; }
        public string Data37 { get; set; }
        public string Data38 { get; set; }
        public string Data39 { get; set; }
        public string Data40 { get; set; }
        public string Data41 { get; set; }
        public string Data42 { get; set; }
        public string Data43 { get; set; }
        public string Data44 { get; set; }
        public string Data45 { get; set; }
        public string Data46 { get; set; }
        public string Data47 { get; set; }
        public string Data48 { get; set; }
        public string Data49 { get; set; }
        public string Data50 { get; set; }
        public string Data51 { get; set; }
        public string Data52 { get; set; }
        public string Data53 { get; set; }
        public string Data54 { get; set; }
        public string Data55 { get; set; }
        public string Data56 { get; set; }
        public string Data57 { get; set; }
        public string Data58 { get; set; }
        public string Data59 { get; set; }
        public string Data60 { get; set; }
        public string Data61 { get; set; }
        public string Data62 { get; set; }
        public string Data63 { get; set; }
        public string Data64 { get; set; }
        public string Data65 { get; set; }
        public string Data66 { get; set; }
        public string Data67 { get; set; }
        public string Data68 { get; set; }
        public string Data69 { get; set; }
        public string Data70 { get; set; }
        public string Data71 { get; set; }
        public string Data72 { get; set; }
        public string Data73 { get; set; }
        public string Data74 { get; set; }
        public string Data75 { get; set; }
        public string Data76 { get; set; }
        public string Data77 { get; set; }
        public string Data78 { get; set; }
        public string Data79 { get; set; }
        public string Data80 { get; set; }
        public string Data81 { get; set; }
        public string Data82 { get; set; }
        public string Data83 { get; set; }
        public string Data84 { get; set; }
        public string Data85 { get; set; }
        public string Data86 { get; set; }
        public string Data87 { get; set; }
        public string Data88 { get; set; }
        public string Data89 { get; set; }
        public string Data90 { get; set; }
        public string Data91 { get; set; }
        public string Data92 { get; set; }
        public string Data93 { get; set; }
        public string Data94 { get; set; }
        public string Data95 { get; set; }
        public string Data96 { get; set; }
        public string Data97 { get; set; }
        public string Data98 { get; set; }
        public string Data99 { get; set; }
        public string Data100 { get; set; }
        public string Data101 { get; set; }
        public string Data102 { get; set; }
        public string Data103 { get; set; }
        public string Data104 { get; set; }
        public string Data105 { get; set; }
        public string Data106 { get; set; }
        public string Data107 { get; set; }
        public string Data108 { get; set; }
        public string Data109 { get; set; }
        public string Data110 { get; set; }
        public string Data111 { get; set; }
        public string Data112 { get; set; }
        public string Data113 { get; set; }
        public string Data114 { get; set; }
        public string Data115 { get; set; }
        public string Data116 { get; set; }
        public string Data117 { get; set; }
        public string Data118 { get; set; }
        public string Data119 { get; set; }
        public string Data120 { get; set; }
        public string Data121 { get; set; }
        public string Data122 { get; set; }
        public string Data123 { get; set; }
        public string Data124 { get; set; }
        public string Data125 { get; set; }
        public string Data126 { get; set; }
        public string Data127 { get; set; }
        public string Data128 { get; set; }
        public string Data129 { get; set; }
        public string Data130 { get; set; }
        public string Data131 { get; set; }
        public string Data132 { get; set; }
        public string Data133 { get; set; }
        public string Data134 { get; set; }
        public string Data135 { get; set; }
        public string Data136 { get; set; }
        public string Data137 { get; set; }
        public string Data138 { get; set; }
        public string Data139 { get; set; }
        public string Data140 { get; set; }
        public string Data141 { get; set; }
        public string Data142 { get; set; }
        public string Data143 { get; set; }
        public string Data144 { get; set; }
        public string Data145 { get; set; }
        public string Data146 { get; set; }
        public string Data147 { get; set; }
        public string Data148 { get; set; }
        public string Data149 { get; set; }
        public string Data150 { get; set; }
        public string Data151 { get; set; }
        public string Data152 { get; set; }
        public string Data153 { get; set; }
        public string Data154 { get; set; }
        public string Data155 { get; set; }
        public string Data156 { get; set; }
        public string Data157 { get; set; }
        public string Data158 { get; set; }
        public string Data159 { get; set; }
        public string Data160 { get; set; }
        public string Data161 { get; set; }
        public string Data162 { get; set; }
        public string Data163 { get; set; }
        public string Data164 { get; set; }
        public string Data165 { get; set; }
        public string Data166 { get; set; }
        public string Data167 { get; set; }
        public string Data168 { get; set; }
        public string Data169 { get; set; }
        public string Data170 { get; set; }
        public string Data171 { get; set; }
        public string Data172 { get; set; }
        public string Data173 { get; set; }
        public string Data174 { get; set; }
        public string Data175 { get; set; }
        public string Data176 { get; set; }
        public string Data177 { get; set; }
        public string Data178 { get; set; }
        public string Data179 { get; set; }
        public string Data180 { get; set; }
    }
}
