using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Pm10000
    {
        public string Bachnumb { get; set; }
        public string Bchsourc { get; set; }
        public string Vchnumwk { get; set; }
        public string Vendorid { get; set; }
        public string Docnumbr { get; set; }
        public short Doctype { get; set; }
        public string Sourcdoc { get; set; }
        public decimal Docamnt { get; set; }
        public DateTime Docdate { get; set; }
        public DateTime Pstgdate { get; set; }
        public string Vaddcdpr { get; set; }
        public string Vadcdtro { get; set; }
        public string Pymtrmid { get; set; }
        public string Taxschid { get; set; }
        public DateTime Duedate { get; set; }
        public decimal Dscdlram { get; set; }
        public DateTime Discdate { get; set; }
        public decimal Prchamnt { get; set; }
        public decimal Chrgamnt { get; set; }
        public decimal Cashamnt { get; set; }
        public string Camcbkid { get; set; }
        public string Cdocnmbr { get; set; }
        public DateTime Camtdate { get; set; }
        public string Campmtnm { get; set; }
        public decimal Chekamnt { get; set; }
        public string Chamcbid { get; set; }
        public DateTime Chekdate { get; set; }
        public string Campynbr { get; set; }
        public decimal Crcrdamt { get; set; }
        public string Ccampynm { get; set; }
        public string Cheknmbr { get; set; }
        public string Cardname { get; set; }
        public string Ccrctnum { get; set; }
        public DateTime Crcarddt { get; set; }
        public string Curncyid { get; set; }
        public string Chekbkid { get; set; }
        public string Trxdscrn { get; set; }
        public decimal Un1099am { get; set; }
        public decimal Trdisamt { get; set; }
        public decimal Taxamnt { get; set; }
        public decimal Frtamnt { get; set; }
        public decimal Ten99amnt { get; set; }
        public decimal Mscchamt { get; set; }
        public string Pordnmbr { get; set; }
        public string Shipmthd { get; set; }
        public decimal Disamtav { get; set; }
        public decimal Distknam { get; set; }
        public decimal Apdstkam { get; set; }
        public decimal Wrofamnt { get; set; }
        public decimal Curtrxam { get; set; }
        public byte Txengcld { get; set; }
        public byte[] Pmwrkmsg { get; set; }
        public byte[] Pmdstmsg { get; set; }
        public decimal Gstdsamt { get; set; }
        public short Pgramsbj { get; set; }
        public decimal Ppsamded { get; set; }
        public short Ppstaxrt { get; set; }
        public short Pstgstus { get; set; }
        public byte Posted { get; set; }
        public decimal Appldamt { get; set; }
        public string Vchrnmbr { get; set; }
        public short Cntrltyp { get; set; }
        public DateTime Modifdt { get; set; }
        public string Mdfusrid { get; set; }
        public DateTime Posteddt { get; set; }
        public string Ptdusrid { get; set; }
        public decimal Noteindx { get; set; }
        public decimal Bktfrtam { get; set; }
        public decimal Bktmscam { get; set; }
        public decimal Bktpuram { get; set; }
        public string Pchschid { get; set; }
        public string Frtschid { get; set; }
        public string Mscschid { get; set; }
        public byte Printed { get; set; }
        public short Prctdisc { get; set; }
        public decimal Retnagam { get; set; }
        public byte Ictrx { get; set; }
        public byte Icdists { get; set; }
        public byte[] Pmicmsgs { get; set; }
        public DateTime TaxDate { get; set; }
        public DateTime Prchdate { get; set; }
        public byte Corrctn { get; set; }
        public byte Simplifd { get; set; }
        public byte Corrnxst { get; set; }
        public string Vchrncor { get; set; }
        public byte[] Pmwrkms2 { get; set; }
        public decimal Bnkrcamt { get; set; }
        public byte Aplywith { get; set; }
        public byte Electronic { get; set; }
        public byte Ectrx { get; set; }
        public byte DocPrinted { get; set; }
        public byte TaxInvReqd { get; set; }
        public decimal BackoutTradeDisc { get; set; }
        public byte Cbvat { get; set; }
        public short Ten99type { get; set; }
        public short Ten99boxnumber { get; set; }
        public short WorkflowStatus { get; set; }
        public DateTime DexRowTs { get; set; }
        public int DexRowId { get; set; }
    }
}
