using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Pm70500
    {
        public short Rptgrind { get; set; }
        public short Rtpachin { get; set; }
        public decimal Rtgrsbin { get; set; }
        public byte Askechtm { get; set; }
        public short Expttype { get; set; }
        public string Filexpnm { get; set; }
        public short Iffilxst { get; set; }
        public string Finrptnm { get; set; }
        public byte Prntofil { get; set; }
        public byte Prtoprtr { get; set; }
        public byte Prtoscrn { get; set; }
        public short Sortby { get; set; }
        public short Sortby2 { get; set; }
        public short Histtype { get; set; }
        public DateTime Pymntdat { get; set; }
        public byte Voidonly { get; set; }
        public byte Exclvoid { get; set; }
        public byte IncludeCanceled { get; set; }
        public DateTime Dateoverdue { get; set; }
        public byte DaysOverdue { get; set; }
        public short PopDateSelection { get; set; }
        public byte IncludeClosed { get; set; }
        public byte IncludeReleased { get; set; }
        public short Ageby { get; set; }
        public short Comptype { get; set; }
        public string Stvndrid { get; set; }
        public string Stvndnam { get; set; }
        public string Stvndcls { get; set; }
        public string Sttstate { get; set; }
        public string Strtzpcd { get; set; }
        public string Strtphon { get; set; }
        public string Strtudef { get; set; }
        public string Sttcntct { get; set; }
        public DateTime StartPoDate { get; set; }
        public string Sttshnam { get; set; }
        public string Sttlocid { get; set; }
        public DateTime StartPromisedDate { get; set; }
        public DateTime StartRequiredDate { get; set; }
        public short Stvnstus { get; set; }
        public short Stt1099t { get; set; }
        public short Stperiod { get; set; }
        public short Strtyear { get; set; }
        public decimal Sttabytd { get; set; }
        public string Strtprty { get; set; }
        public DateTime Sttduedt { get; set; }
        public DateTime Stdiscdt { get; set; }
        public short Alorange { get; set; }
        public string Sttacncd { get; set; }
        public string Stdocnum { get; set; }
        public DateTime Sttdocdt { get; set; }
        public short Stdoctyp { get; set; }
        public string Stvchnum { get; set; }
        public string Sttitnum { get; set; }
        public string Stchknum { get; set; }
        public DateTime Sttchkdt { get; set; }
        public string Stchbkid { get; set; }
        public string Stbchsrc { get; set; }
        public string Stbchnum { get; set; }
        public DateTime Stpstddt { get; set; }
        public string Stclsdsc { get; set; }
        public string Endvndid { get; set; }
        public string Endvndnm { get; set; }
        public string Endvncls { get; set; }
        public string Endstate { get; set; }
        public string Endzipcd { get; set; }
        public string Enphonbr { get; set; }
        public DateTime EndPoDate { get; set; }
        public string Enusrdef { get; set; }
        public string Endlocid { get; set; }
        public string Enitmnbr { get; set; }
        public DateTime EndRequiredDate { get; set; }
        public DateTime EndPromisedDate { get; set; }
        public string Endvndct { get; set; }
        public string Endshnam { get; set; }
        public short Envnstts { get; set; }
        public short E1099typ { get; set; }
        public short Endperod { get; set; }
        public short Endyear { get; set; }
        public decimal Enambytd { get; set; }
        public string Enpryrty { get; set; }
        public DateTime Endduedt { get; set; }
        public DateTime Endiscdt { get; set; }
        public short Alornge2 { get; set; }
        public string Enaucncd { get; set; }
        public string Endocnum { get; set; }
        public DateTime Enddocdt { get; set; }
        public short Endoctyp { get; set; }
        public string Envchnum { get; set; }
        public string Enchknum { get; set; }
        public DateTime Endchkdt { get; set; }
        public string Enchbkid { get; set; }
        public string Enbchsrc { get; set; }
        public string Endbnmbr { get; set; }
        public DateTime Enpstddt { get; set; }
        public string Encldscr { get; set; }
        public DateTime Agngdate { get; set; }
        public short Pbsdcdtk { get; set; }
        public short Pbsdudtk { get; set; }
        public short Pbsdsdtk { get; set; }
        public short Pbschdtk { get; set; }
        public short Pbsptdtk { get; set; }
        public short Pbedcdtk { get; set; }
        public short Pbedudtk { get; set; }
        public short Pbedsdtk { get; set; }
        public short Pbechdtk { get; set; }
        public short Pbepdtkn { get; set; }
        public short Pbcdttkn { get; set; }
        public byte Detldrpt { get; set; }
        public byte Singact { get; set; }
        public string Sttacnum1 { get; set; }
        public string Sttacnum2 { get; set; }
        public string Sttacnum3 { get; set; }
        public string Sttacnum4 { get; set; }
        public string Sttacnum5 { get; set; }
        public string Eaccnbr1 { get; set; }
        public string Eaccnbr2 { get; set; }
        public string Eaccnbr3 { get; set; }
        public string Eaccnbr4 { get; set; }
        public string Eaccnbr5 { get; set; }
        public string Strponum { get; set; }
        public string Endponum { get; set; }
        public string EndPoprcptNum { get; set; }
        public string StartPoprcptNum { get; set; }
        public string Strcreat { get; set; }
        public DateTime Strctdt { get; set; }
        public DateTime Enrctdt { get; set; }
        public string Strctnum { get; set; }
        public string Enrctnbr { get; set; }
        public string Endcreate { get; set; }
        public short Strposta { get; set; }
        public short Endposta { get; set; }
        public byte Incrcpts { get; set; }
        public byte Dissrlot { get; set; }
        public string Strxsrc { get; set; }
        public string Entrxsrc { get; set; }
        public byte Crblnccb { get; set; }
        public byte Fllypdcb { get; set; }
        public byte Zrobalcb { get; set; }
        public byte Exclzbal { get; set; }
        public byte Noactvcb { get; set; }
        public byte UnpostedAppliedCrDocs { get; set; }
        public byte MulticurrencyInformation { get; set; }
        public byte[] IncludeDistributionTyp { get; set; }
        public decimal Rptxrate { get; set; }
        public short Rprtclmd { get; set; }
        public short Prtcurin { get; set; }
        public byte Inclfunc { get; set; }
        public short Startlineorigin { get; set; }
        public short Endlineorigin { get; set; }
        public string Startbuyerid { get; set; }
        public string Endbuyerid { get; set; }
        public byte Includeholdpo { get; set; }
        public byte Includeholdpoonly { get; set; }
        public DateTime Startreleasebydate { get; set; }
        public DateTime Endreleasebydate { get; set; }
        public byte IncludeNew { get; set; }
        public byte IncludeChangeOrder { get; set; }
        public byte IncludeReceived { get; set; }
        public short SummaryYear { get; set; }
        public short DateSensitivitySumSelect { get; set; }
        public string StartProjNum { get; set; }
        public string EndProjNum { get; set; }
        public string StartCostCatId { get; set; }
        public string EndCostCatId { get; set; }
        public byte IncludeApprovedPosOnly { get; set; }
        public byte Misc { get; set; }
        public byte Interest { get; set; }
        public byte Dividend { get; set; }
        public int DexRowId { get; set; }
    }
}
