using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Rm00700
    {
        public short Agngdtkn { get; set; }
        public short Rangeby { get; set; }
        public byte Prtdbrcd { get; set; }
        public byte Prpstjcb { get; set; }
        public byte Prsbdrcb { get; set; }
        public DateTime Enddocdt { get; set; }
        public string Filexpnm { get; set; }
        public string Finrptnm { get; set; }
        public byte Askechtm { get; set; }
        public byte Inclgnds { get; set; }
        public short Iffilxst { get; set; }
        public short Expttype { get; set; }
        public byte Prntnots { get; set; }
        public short Cstsrtby { get; set; }
        public byte Prntofil { get; set; }
        public byte Prtoprtr { get; set; }
        public byte Prtoscrn { get; set; }
        public short Prnttype { get; set; }
        public short Rptgrind { get; set; }
        public decimal Rtgrsbin { get; set; }
        public short Rtpachin { get; set; }
        public short Sortby { get; set; }
        public string Enfulnam { get; set; }
        public string Endaddct { get; set; }
        public string Endclsid { get; set; }
        public string Encustid { get; set; }
        public string Encstnam { get; set; }
        public string Endphon1 { get; set; }
        public string Enslster { get; set; }
        public string Enspsnid { get; set; }
        public string Endshnam { get; set; }
        public string Endstate { get; set; }
        public string Enusrdf1 { get; set; }
        public string Endzipcd { get; set; }
        public DateTime Endingdt { get; set; }
        public string Encldscr { get; set; }
        public string Enlstnam { get; set; }
        public string Endvendr { get; set; }
        public string Endemply { get; set; }
        public string Endcity { get; set; }
        public string Endocnum { get; set; }
        public short Endoctyp { get; set; }
        public short Endperod { get; set; }
        public DateTime Endpstdt { get; set; }
        public string Endbnmbr { get; set; }
        public string Enbchsrc { get; set; }
        public string Entrxsrc { get; set; }
        public short Enrmtkdt { get; set; }
        public decimal Enslsamt { get; set; }
        public decimal Enprmrgn { get; set; }
        public string Strtflnm { get; set; }
        public short Strmtkdt { get; set; }
        public string Staddctt { get; set; }
        public string Sttclsid { get; set; }
        public string Stcustid { get; set; }
        public string Stcustnm { get; set; }
        public DateTime Strtdate { get; set; }
        public DateTime Strtngdt { get; set; }
        public string Sttphon1 { get; set; }
        public string Stslster { get; set; }
        public string Stsprsid { get; set; }
        public string Sttshnam { get; set; }
        public string Sttstate { get; set; }
        public string Sttudef1 { get; set; }
        public string Strtzpcd { get; set; }
        public string Stclsdsc { get; set; }
        public string Sttlstnm { get; set; }
        public string Strtvndr { get; set; }
        public string Strtempl { get; set; }
        public string Strtcity { get; set; }
        public short Stmtcycl { get; set; }
        public short Enstcycl { get; set; }
        public string Stdocnum { get; set; }
        public short Sttdoctp { get; set; }
        public DateTime Sttdocdt { get; set; }
        public short Stperiod { get; set; }
        public DateTime Sttpstdt { get; set; }
        public string Stbchnum { get; set; }
        public string Stbchsrc { get; set; }
        public string Strxsrc { get; set; }
        public decimal Stprmrgn { get; set; }
        public decimal Stslsamt { get; set; }
        public byte Inactive { get; set; }
        public short Balnctyp { get; set; }
        public byte Active { get; set; }
        public short Histtype { get; set; }
        public byte Trantopr { get; set; }
        public byte Prntdtld { get; set; }
        public DateTime Cutofdat { get; set; }
        public byte Crblnccb { get; set; }
        public byte Fllypdcb { get; set; }
        public byte Noactvcb { get; set; }
        public byte Zrobalcb { get; set; }
        public byte Pastducb { get; set; }
        public short Whichrpt { get; set; }
        public short Pertypgb { get; set; }
        public short Year1 { get; set; }
        public string Sttacnum1 { get; set; }
        public string Sttacnum2 { get; set; }
        public string Sttacnum3 { get; set; }
        public string Sttacnum4 { get; set; }
        public string Sttacnum5 { get; set; }
        public string Eaccnbr1 { get; set; }
        public string Eaccnbr2 { get; set; }
        public string Eaccnbr3 { get; set; }
        public string Eaccnbr4 { get; set; }
        public string Eaccnbr5 { get; set; }
        public short Segmntrg { get; set; }
        public string Enitmnbr { get; set; }
        public string Endserlt { get; set; }
        public string Sttitnum { get; set; }
        public string Strtsrlt { get; set; }
        public short Trxtype { get; set; }
        public byte Incltxdt { get; set; }
        public byte Inclpymt { get; set; }
        public DateTime Stquoexd { get; set; }
        public DateTime Edquoexd { get; set; }
        public DateTime Streqdat { get; set; }
        public DateTime Endreqdt { get; set; }
        public string Sttloccd { get; set; }
        public string Enlocncd { get; set; }
        public int Stmstnmb { get; set; }
        public int Edmasnmb { get; set; }
        public string Stprhdid { get; set; }
        public string Enprhdid { get; set; }
        public string Sttdocid { get; set; }
        public string Enddocid { get; set; }
        public short Stsoptyp { get; set; }
        public short Edsoptyp { get; set; }
        public byte Discomp { get; set; }
        public byte Disprchd { get; set; }
        public byte Dissrlot { get; set; }
        public byte Disusrdf { get; set; }
        public byte Exccomp { get; set; }
        public byte Excfulfil { get; set; }
        public byte Incmcinf { get; set; }
        public decimal Rptxrate { get; set; }
        public short Rprtclmd { get; set; }
        public short Prtcurin { get; set; }
        public byte Connaact { get; set; }
        public short DateSensitivitySumSelect { get; set; }
        public short SummaryYear { get; set; }
        public int DexRowId { get; set; }
    }
}
