using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Rm10301
    {
        public short Doctype { get; set; }
        public short Rmdtypal { get; set; }
        public string Rmdnumwk { get; set; }
        public string Docnumbr { get; set; }
        public string Docprfix { get; set; }
        public string Docdescr { get; set; }
        public DateTime Docdate { get; set; }
        public string Bachnumb { get; set; }
        public string Bchsourc { get; set; }
        public decimal Noteindx { get; set; }
        public string Custnmbr { get; set; }
        public string Custname { get; set; }
        public string Adrscode { get; set; }
        public string Slprsnid { get; set; }
        public string Salsterr { get; set; }
        public short Comappto { get; set; }
        public decimal Comdlram { get; set; }
        public decimal Ncomamnt { get; set; }
        public string Shipmthd { get; set; }
        public string Cstponbr { get; set; }
        public string Taxschid { get; set; }
        public string Slschdid { get; set; }
        public string Frtschid { get; set; }
        public string Mscschid { get; set; }
        public decimal Costamnt { get; set; }
        public decimal Slsamnt { get; set; }
        public decimal Trdisamt { get; set; }
        public short Trddisct { get; set; }
        public decimal Frtamnt { get; set; }
        public decimal Miscamnt { get; set; }
        public decimal Taxamnt { get; set; }
        public decimal Bktslsam { get; set; }
        public decimal Bktfrtam { get; set; }
        public decimal Bktmscam { get; set; }
        public byte Txengcld { get; set; }
        public decimal Docamnt { get; set; }
        public decimal Appldamt { get; set; }
        public decimal Cashamnt { get; set; }
        public string Cbkidcsh { get; set; }
        public DateTime Cashdate { get; set; }
        public string Dcnumcsh { get; set; }
        public decimal Chekamnt { get; set; }
        public string Cbkidchk { get; set; }
        public string Cbkidcrd { get; set; }
        public string Cheknmbr { get; set; }
        public DateTime Chekdate { get; set; }
        public string Dcnumchk { get; set; }
        public decimal Crcrdamt { get; set; }
        public string Crcrdnam { get; set; }
        public string Rctnccrd { get; set; }
        public DateTime Crcarddt { get; set; }
        public string Dcnumcrd { get; set; }
        public decimal Discrtnd { get; set; }
        public decimal Distknam { get; set; }
        public decimal Disavtkn { get; set; }
        public decimal Wrofamnt { get; set; }
        public decimal Ppsamded { get; set; }
        public decimal Gstdsamt { get; set; }
        public decimal Acctamnt { get; set; }
        public string Pymtrmid { get; set; }
        public decimal Disavamt { get; set; }
        public DateTime Discdate { get; set; }
        public DateTime Duedate { get; set; }
        public decimal Dscdlram { get; set; }
        public short Dscpctam { get; set; }
        public string Curncyid { get; set; }
        public byte Posted { get; set; }
        public DateTime Lstedtdt { get; set; }
        public string Lstusred { get; set; }
        public byte[] Rmtremsg { get; set; }
        public byte[] Rmdpemsg { get; set; }
        public DateTime Glpostdt { get; set; }
        public DateTime Posteddt { get; set; }
        public string Ptdusrid { get; set; }
        public DateTime TaxDate { get; set; }
        public byte Aplywith { get; set; }
        public DateTime Saledate { get; set; }
        public byte Corrctn { get; set; }
        public byte Simplifd { get; set; }
        public byte Corrnxst { get; set; }
        public string Docncorr { get; set; }
        public byte[] Rmtremsg2 { get; set; }
        public byte DocPrinted { get; set; }
        public short Disgrper { get; set; }
        public short Duegrper { get; set; }
        public byte Electronic { get; set; }
        public byte Ectrx { get; set; }
        public short Pstgstus { get; set; }
        public decimal BackoutTradeDisc { get; set; }
        public byte Directdebit { get; set; }
        public byte Eftflag { get; set; }
        public DateTime DexRowTs { get; set; }
        public int DexRowId { get; set; }
    }
}
