using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Svc00998
    {
        public decimal Sequence1 { get; set; }
        public short Srvrectype { get; set; }
        public byte Mulequip { get; set; }
        public byte Mulcodes { get; set; }
        public byte Multech { get; set; }
        public string Timezone { get; set; }
        public string Srvtype { get; set; }
        public string Offid { get; set; }
        public string Locncode { get; set; }
        public string Srvstat { get; set; }
        public string BackorderStatus { get; set; }
        public string IntransitStatus { get; set; }
        public string DispatchStatus { get; set; }
        public string ArrivalStatus { get; set; }
        public string CompleteStatus { get; set; }
        public string Postat { get; set; }
        public byte SinglePo { get; set; }
        public string Srlstat { get; set; }
        public string Retstatus { get; set; }
        public byte Cksvcarea { get; set; }
        public byte Ckskill { get; set; }
        public short Consts { get; set; }
        public string Pricshed { get; set; }
        public string Cnttype { get; set; }
        public string Mapprloc { get; set; }
        public string Usrdfpr1 { get; set; }
        public string Usrdrpr2 { get; set; }
        public string Usrdrpr3 { get; set; }
        public string Usrdrpr4 { get; set; }
        public string Usrdrpr5 { get; set; }
        public short Numdaysod { get; set; }
        public short Numdayspm { get; set; }
        public short Numdayscb { get; set; }
        public byte Chghist { get; set; }
        public byte Autocust { get; set; }
        public string Custnmbr { get; set; }
        public string Retcstnr { get; set; }
        public byte Pageon { get; set; }
        public string Pageprofile { get; set; }
        public string Prclevel { get; set; }
        public byte UseSop { get; set; }
        public string PasswordArray1 { get; set; }
        public string PasswordArray2 { get; set; }
        public string PasswordArray3 { get; set; }
        public string PasswordArray4 { get; set; }
        public string PasswordArray5 { get; set; }
        public string PasswordArray6 { get; set; }
        public string PasswordArray7 { get; set; }
        public byte CheckCustomer { get; set; }
        public byte CheckCustomerAddress { get; set; }
        public byte CheckSerial { get; set; }
        public byte EmailTech { get; set; }
        public short UsePop { get; set; }
        public byte PrintToWeb { get; set; }
        public byte CheckCallBack { get; set; }
        public short RetainagePercent { get; set; }
        public string Rettype { get; set; }
        public string RtvType { get; set; }
        public short SvcPoValidation { get; set; }
        public string LocationCodeVendor { get; set; }
        public short Worectype { get; set; }
        public string WoOfficeId { get; set; }
        public string WoTimeZone { get; set; }
        public string Woentsta { get; set; }
        public string Wobostat { get; set; }
        public string Wocompstat { get; set; }
        public string Wowipstat { get; set; }
        public string Wotype { get; set; }
        public string Wolocat { get; set; }
        public string PartsAvailableStatus { get; set; }
        public short SvcAddressOption { get; set; }
        public byte SvcDisableXfrGrouping { get; set; }
        public string ReadyToInvoiceStatus { get; set; }
        public string InvoicedStatus { get; set; }
        public short SvcAutoCreateLabor { get; set; }
        public string Usrdrpr6 { get; set; }
        public string Usrdrpr7 { get; set; }
        public string Usrdrpr8 { get; set; }
        public string Usrdrpr9 { get; set; }
        public string Usrdrp10 { get; set; }
        public string SvcUserDefinePrompt1 { get; set; }
        public string SvcUserDefinePrompt2 { get; set; }
        public string SvcUserDefinePrompt3 { get; set; }
        public string SvcUserDefinePrompt4 { get; set; }
        public string SvcUserDefinePrompt5 { get; set; }
        public string SvcUserDefinePrompt6 { get; set; }
        public string SvcUserDefinePrompt7 { get; set; }
        public string SvcUserDefinePrompt8 { get; set; }
        public string SvcUserDefinePrompt9 { get; set; }
        public string SvcUserDefinePrompt10 { get; set; }
        public string SvcUserDefinePrompt11 { get; set; }
        public string SvcUserDefinePrompt12 { get; set; }
        public string SvcUserDefinePrompt13 { get; set; }
        public string SvcUserDefinePrompt14 { get; set; }
        public string SvcUserDefinePrompt15 { get; set; }
        public short SvcCheckScLabor { get; set; }
        public short SvcCheckWoLabor { get; set; }
        public byte SvcCheckCallBack { get; set; }
        public string SvcServiceType { get; set; }
        public string SvcDirectory { get; set; }
        public string SvcReturnPriceLevel { get; set; }
        public short SvcTransferOption { get; set; }
        public string SvcServiceBatchId { get; set; }
        public string SvcServiceDocumentId { get; set; }
        public string SvcContractBatchId { get; set; }
        public string SvcContractDocumentId { get; set; }
        public byte SvcUseReturn { get; set; }
        public short SvcDupSerial { get; set; }
        public byte SvcAutoSopContract { get; set; }
        public byte SvcContractWarranty { get; set; }
        public byte SvcCreateSerial { get; set; }
        public short SvcVendorWarrantyFlag { get; set; }
        public short SvcSellerWarrantyFlag { get; set; }
        public byte SvcCreatePopSerial { get; set; }
        public byte SvcItemDelta { get; set; }
        public byte SvcAllowContract0Sop { get; set; }
        public byte SvcAllowService0Sop { get; set; }
        public string SvcCCreditBatchId { get; set; }
        public string SvcCCreditDocumentId { get; set; }
        public string SvcSCreditBatchId { get; set; }
        public string SvcSCreditDocumentId { get; set; }
        public string SvcZeroBatchId { get; set; }
        public string SvcZeroDocumentId { get; set; }
        public byte SvcAutoCreditReceipt { get; set; }
        public byte SvcAutoReplaceReceipt { get; set; }
        public string SvcRmaInvoiceBatchId { get; set; }
        public string SvcRmaCreditBatchId { get; set; }
        public string SvcRmaOrderBatchId { get; set; }
        public string CallTo { get; set; }
        public string CallFrom { get; set; }
        public short PriorityLevel { get; set; }
        public string SvcUserDefinePrompt16 { get; set; }
        public string SvcUserDefinePrompt17 { get; set; }
        public string SvcUserDefinePrompt18 { get; set; }
        public string SvcUserDefinePrompt19 { get; set; }
        public string SvcUserDefinePrompt20 { get; set; }
        public byte SvcAutoXshipReceipt { get; set; }
        public byte SvcUsePayable { get; set; }
        public byte SvcPrePaidOverride { get; set; }
        public byte SvcDistHistoryContract { get; set; }
        public byte SvcDistHistoryRma { get; set; }
        public byte SvcDistHistoryRtv { get; set; }
        public byte SvcDistHistoryService { get; set; }
        public byte SvcDistHistoryTransfer { get; set; }
        public byte SvcDistHistoryWorkOrd { get; set; }
        public byte SvcUseSameNumber { get; set; }
        public string SvcInStockCustomer { get; set; }
        public string SvcInStockStatus { get; set; }
        public byte SvcCreateNonSerialEq { get; set; }
        public byte SvcAllowRma0Sop { get; set; }
        public byte SvcUseReturnPriceLev { get; set; }
        public byte SvcSupersessionEnabled { get; set; }
        public byte Autoren { get; set; }
        public short SvcDaysToRenew { get; set; }
        public decimal Mxincpct { get; set; }
        public decimal Pctcryfwd { get; set; }
        public byte SvcRemovePriceOverrid { get; set; }
        public string Renprcschd { get; set; }
        public byte Cnsoldtd { get; set; }
        public byte SvcDonotCombinePm { get; set; }
        public byte SvcContractPmonly { get; set; }
        public byte SvcAutoMoveHistory { get; set; }
        public byte SvcAllowNonInventoried { get; set; }
        public byte SvcUsePayRate { get; set; }
        public short SvcUsePayroll { get; set; }
        public string SvcDefaultWorkType1 { get; set; }
        public string SvcDefaultWorkType2 { get; set; }
        public string SvcDefaultWorkType3 { get; set; }
        public string SvcDefaultWorkType4 { get; set; }
        public string SvcDefaultWorkType5 { get; set; }
        public short SvcBillingExchangeRate { get; set; }
        public short SvcRevenueExchangeRate { get; set; }
        public byte SvcConsolidateSoporder { get; set; }
        public byte SvcCreateMaequipment { get; set; }
        public byte SvcCreateManonSerialEq { get; set; }
        public int DexRowId { get; set; }
    }
}
