using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Svc05200
    {
        public string Retdocid { get; set; }
        public short ReturnRecordType { get; set; }
        public decimal Lnseqnbr { get; set; }
        public decimal SvcNextLineSeqNumber { get; set; }
        public decimal SvcPrevLineSeqNumber { get; set; }
        public string Rettype { get; set; }
        public short RmaStatus { get; set; }
        public string Retstat { get; set; }
        public byte Received { get; set; }
        public byte TravelerPrinted { get; set; }
        public byte SvcReadyToClose { get; set; }
        public string SvcRmaReasonCode { get; set; }
        public string SvcRmaReasonCodeDesc { get; set; }
        public decimal Noteindx { get; set; }
        public short Retorig { get; set; }
        public string Retref { get; set; }
        public short Srvrectype { get; set; }
        public string Callnbr { get; set; }
        public int Eqpline { get; set; }
        public int Lnitmseq { get; set; }
        public byte SvcRmaFromService { get; set; }
        public short Soptype { get; set; }
        public string Sopnumbe { get; set; }
        public int Cmpntseq { get; set; }
        public int SopLineItemSequence { get; set; }
        public DateTime Entdte { get; set; }
        public DateTime Enttme { get; set; }
        public DateTime Etadte { get; set; }
        public DateTime Etatme { get; set; }
        public DateTime CommitDate { get; set; }
        public DateTime CommitTime { get; set; }
        public DateTime Retudate { get; set; }
        public DateTime ReturnTime { get; set; }
        public DateTime Compdte { get; set; }
        public DateTime Comptme { get; set; }
        public DateTime Prmdate { get; set; }
        public string Refrence { get; set; }
        public string Userid { get; set; }
        public string Offid { get; set; }
        public string Locncode { get; set; }
        public string Rtrnname { get; set; }
        public string Retaddr1 { get; set; }
        public string Retaddr2 { get; set; }
        public string Retaddr3 { get; set; }
        public string Rtrncity { get; set; }
        public string SvcReturnState { get; set; }
        public string Rtrnzip { get; set; }
        public string ReturnCountry { get; set; }
        public string Custnmbr { get; set; }
        public string Custname { get; set; }
        public string Adrscode { get; set; }
        public string Contact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string BillToCustomer { get; set; }
        public string SvcBillToAddressCode { get; set; }
        public string Cstponbr { get; set; }
        public decimal Quantity { get; set; }
        public short Decplqty { get; set; }
        public string Uofm { get; set; }
        public string Itemnmbr { get; set; }
        public string Itemdesc { get; set; }
        public decimal Unitcost { get; set; }
        public decimal Oruntcst { get; set; }
        public decimal Extdcost { get; set; }
        public decimal Orextcst { get; set; }
        public decimal Unitprce { get; set; }
        public decimal Oruntprc { get; set; }
        public decimal Xtndprce { get; set; }
        public decimal Oxtndprc { get; set; }
        public byte Custown { get; set; }
        public byte Factseal { get; set; }
        public string Orddocid { get; set; }
        public int Translineseq { get; set; }
        public short Status { get; set; }
        public decimal FlatRateRepairPrice { get; set; }
        public decimal OrigFlatRepairPrice { get; set; }
        public decimal RepairPrice { get; set; }
        public decimal OriginatingRepairPrice { get; set; }
        public decimal NtePrice { get; set; }
        public decimal OriginatingNtePrice { get; set; }
        public decimal RepairCost { get; set; }
        public decimal OriginatingRepairCost { get; set; }
        public string BillOfLading { get; set; }
        public string Shipmthd { get; set; }
        public short CreditSopType { get; set; }
        public string CreditSopNumber { get; set; }
        public int CreditSopLineItemSeq { get; set; }
        public short ReplaceSopType { get; set; }
        public string ReplaceSopNumber { get; set; }
        public int ReplaceSopLineItemSe { get; set; }
        public string LocationCodeReplacemen { get; set; }
        public string ReplaceItemNumber { get; set; }
        public string ReplaceUOfM { get; set; }
        public string ReplacePriceLevel { get; set; }
        public decimal ReplaceQty { get; set; }
        public decimal ReplaceCost { get; set; }
        public decimal OriginatingReplaceCost { get; set; }
        public decimal ReplacePrice { get; set; }
        public decimal OriginatingReplacePric { get; set; }
        public string SopNumberInvoice { get; set; }
        public string ItemNumberInvoice { get; set; }
        public string Userdef1 { get; set; }
        public string Userdef2 { get; set; }
        public string Usrdef03 { get; set; }
        public string Usrdef04 { get; set; }
        public string Usrdef05 { get; set; }
        public short Currnidx { get; set; }
        public short Decplcur { get; set; }
        public short Odecplcu { get; set; }
        public string ReturnItemNumber { get; set; }
        public string ReturnItemDescription { get; set; }
        public string ReturnLocationCode { get; set; }
        public decimal ReturnQty { get; set; }
        public string ReturnUOfM { get; set; }
        public decimal Retcost { get; set; }
        public decimal OriginatingReturnCost { get; set; }
        public decimal SvcExtendedReturnCost { get; set; }
        public decimal SvcOrigExtReturnCost { get; set; }
        public string SvcReturnPriceLevel { get; set; }
        public decimal SvcReturnPrice { get; set; }
        public decimal OriginatingReturnPrice { get; set; }
        public decimal SvcExtendedReturnPric { get; set; }
        public decimal SvcOrigExtReturnPric { get; set; }
        public string SvcFoId { get; set; }
        public short SvcScmComplete { get; set; }
        public short SvcRmakitComponentFrom { get; set; }
        public int SvcRmacomponentSeq { get; set; }
        public decimal Cmpitqty { get; set; }
        public decimal Qtyonhnd { get; set; }
        public decimal Qtyrtrnd { get; set; }
        public decimal Qtyinuse { get; set; }
        public decimal Qtyinsvc { get; set; }
        public decimal Qtydmged { get; set; }
        public byte SvcReverseFlag { get; set; }
        public byte SvcRmaallocated { get; set; }
        public int DexRowId { get; set; }
    }
}
