using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Svc30607
    {
        public short Consts { get; set; }
        public string Contnbr { get; set; }
        public decimal Lnseqnbr { get; set; }
        public int MeterBases1 { get; set; }
        public int MeterBases2 { get; set; }
        public int MeterBases3 { get; set; }
        public int MeterBases4 { get; set; }
        public int MeterBases5 { get; set; }
        public int MeterOverages1 { get; set; }
        public int MeterOverages2 { get; set; }
        public int MeterOverages3 { get; set; }
        public int MeterOverages4 { get; set; }
        public int MeterOverages5 { get; set; }
        public int MeterOverages6 { get; set; }
        public int MeterOverages7 { get; set; }
        public int MeterOverages8 { get; set; }
        public int MeterOverages9 { get; set; }
        public int MeterOverages10 { get; set; }
        public int MeterOverages11 { get; set; }
        public int MeterOverages12 { get; set; }
        public int MeterOverages13 { get; set; }
        public int MeterOverages14 { get; set; }
        public int MeterOverages15 { get; set; }
        public int MeterOverages16 { get; set; }
        public int MeterOverages17 { get; set; }
        public int MeterOverages18 { get; set; }
        public int MeterOverages19 { get; set; }
        public int MeterOverages20 { get; set; }
        public decimal MeterCharges1 { get; set; }
        public decimal MeterCharges2 { get; set; }
        public decimal MeterCharges3 { get; set; }
        public decimal MeterCharges4 { get; set; }
        public decimal MeterCharges5 { get; set; }
        public decimal MeterCharges6 { get; set; }
        public decimal MeterCharges7 { get; set; }
        public decimal MeterCharges8 { get; set; }
        public decimal MeterCharges9 { get; set; }
        public decimal MeterCharges10 { get; set; }
        public decimal MeterCharges11 { get; set; }
        public decimal MeterCharges12 { get; set; }
        public decimal MeterCharges13 { get; set; }
        public decimal MeterCharges14 { get; set; }
        public decimal MeterCharges15 { get; set; }
        public decimal MeterCharges16 { get; set; }
        public decimal MeterCharges17 { get; set; }
        public decimal MeterCharges18 { get; set; }
        public decimal MeterCharges19 { get; set; }
        public decimal MeterCharges20 { get; set; }
        public byte MeterExpires1 { get; set; }
        public byte MeterExpires2 { get; set; }
        public byte MeterExpires3 { get; set; }
        public byte MeterExpires4 { get; set; }
        public byte MeterExpires5 { get; set; }
        public int MeterInternalUses1 { get; set; }
        public int MeterInternalUses2 { get; set; }
        public int MeterInternalUses3 { get; set; }
        public int MeterInternalUses4 { get; set; }
        public int MeterInternalUses5 { get; set; }
        public int MeterActuals1 { get; set; }
        public int MeterActuals2 { get; set; }
        public int MeterActuals3 { get; set; }
        public int MeterActuals4 { get; set; }
        public int MeterActuals5 { get; set; }
        public int MeterStartings1 { get; set; }
        public int MeterStartings2 { get; set; }
        public int MeterStartings3 { get; set; }
        public int MeterStartings4 { get; set; }
        public int MeterStartings5 { get; set; }
        public decimal AmountToInvoice { get; set; }
        public decimal InvoicedAmount { get; set; }
        public decimal TotalInvoiced { get; set; }
        public DateTime Invodate { get; set; }
        public decimal OrigAmountToInvoice { get; set; }
        public decimal OrigInvoicedAmount { get; set; }
        public decimal OrigTotalInvoiced { get; set; }
        public decimal OriginatingMeterCharge1 { get; set; }
        public decimal OriginatingMeterCharge2 { get; set; }
        public decimal OriginatingMeterCharge3 { get; set; }
        public decimal OriginatingMeterCharge4 { get; set; }
        public decimal OriginatingMeterCharge5 { get; set; }
        public decimal OriginatingMeterCharge6 { get; set; }
        public decimal OriginatingMeterCharge7 { get; set; }
        public decimal OriginatingMeterCharge8 { get; set; }
        public decimal OriginatingMeterCharge9 { get; set; }
        public decimal OriginatingMeterCharge10 { get; set; }
        public decimal OriginatingMeterCharge11 { get; set; }
        public decimal OriginatingMeterCharge12 { get; set; }
        public decimal OriginatingMeterCharge13 { get; set; }
        public decimal OriginatingMeterCharge14 { get; set; }
        public decimal OriginatingMeterCharge15 { get; set; }
        public decimal OriginatingMeterCharge16 { get; set; }
        public decimal OriginatingMeterCharge17 { get; set; }
        public decimal OriginatingMeterCharge18 { get; set; }
        public decimal OriginatingMeterCharge19 { get; set; }
        public decimal OriginatingMeterCharge20 { get; set; }
        public short SvcContractVersion { get; set; }
        public int DexRowId { get; set; }
    }
}
