using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Svc70500
    {
        public short Prtbysit { get; set; }
        public short Prntoptn { get; set; }
        public string Sttgndsc { get; set; }
        public string Engendsc { get; set; }
        public string Enusrcat1 { get; set; }
        public string Enusrcat2 { get; set; }
        public string Enusrcat3 { get; set; }
        public string Enusrcat4 { get; set; }
        public string Enusrcat5 { get; set; }
        public string Enusrcat6 { get; set; }
        public string Strtucat1 { get; set; }
        public string Strtucat2 { get; set; }
        public string Strtucat3 { get; set; }
        public string Strtucat4 { get; set; }
        public string Strtucat5 { get; set; }
        public string Strtucat6 { get; set; }
        public string Callnbst { get; set; }
        public string Callnmen { get; set; }
        public string Contnbrs { get; set; }
        public string Contnbre { get; set; }
        public string Srlnbrst { get; set; }
        public string Srlnbren { get; set; }
        public string Pmdtlids { get; set; }
        public string Pmdtlide { get; set; }
        public string Stcustid { get; set; }
        public string Encustid { get; set; }
        public string Sttechid { get; set; }
        public string Entechid { get; set; }
        public string Stoffid { get; set; }
        public string Enoffid { get; set; }
        public string Svcopt1 { get; set; }
        public string Endsvco1 { get; set; }
        public string Stsvcop1 { get; set; }
        public string Ensvcop2 { get; set; }
        public string Stsvcopt3 { get; set; }
        public string Ensvcop3 { get; set; }
        public string Stsvcop4 { get; set; }
        public string Ensvcop4 { get; set; }
        public byte Stsvcop5 { get; set; }
        public byte Ensvcop5 { get; set; }
        public string Stsvcop6 { get; set; }
        public string Ensvcop6 { get; set; }
        public string Stsvcop7 { get; set; }
        public string Ensvcop7 { get; set; }
        public string Stsvcop8 { get; set; }
        public string Ensvcop8 { get; set; }
        public short Stsvcop9 { get; set; }
        public short Ensvcop9 { get; set; }
        public short Stsvco10 { get; set; }
        public short Ensvco10 { get; set; }
        public string Sttitnum { get; set; }
        public string Enitmnbr { get; set; }
        public short Srvrectype { get; set; }
        public short Consts { get; set; }
        public short Prvdrinf { get; set; }
        public byte Prtdscnt { get; set; }
        public byte Prtsvchs { get; set; }
        public string Svcrptnm { get; set; }
        public byte Prntnots { get; set; }
        public short Prnttype { get; set; }
        public byte Askechtm { get; set; }
        public byte Inclgnds { get; set; }
        public byte Prntofil { get; set; }
        public byte Prtoprtr { get; set; }
        public byte Prtoscrn { get; set; }
        public short Iffilxst { get; set; }
        public string Filexpnm { get; set; }
        public short Expttype { get; set; }
        public short Rptgrind { get; set; }
        public string Sttclass { get; set; }
        public string Endclass { get; set; }
        public string Strtdscr { get; set; }
        public string Enddescr { get; set; }
        public string Sttsched { get; set; }
        public string Enschdul { get; set; }
        public string Sttloccd { get; set; }
        public string Enlocncd { get; set; }
        public string Sttlotty { get; set; }
        public string Enlottyp { get; set; }
        public DateTime Strtngdt { get; set; }
        public DateTime Endingdt { get; set; }
        public short Endtkndt { get; set; }
        public short Sttokndt { get; set; }
        public string Strctnum { get; set; }
        public string Enrctnbr { get; set; }
        public short Rtpachin { get; set; }
        public decimal Rtgrsbin { get; set; }
        public short Sortby { get; set; }
        public byte Prtsrlot { get; set; }
        public byte Inzroqty { get; set; }
        public byte Prtitqty { get; set; }
        public string Sttbinum { get; set; }
        public string Enbinnbr { get; set; }
        public string Stdocnum { get; set; }
        public string Endocnum { get; set; }
        public short Stdoctyp { get; set; }
        public short Endoctyp { get; set; }
        public string Sttmodul { get; set; }
        public string Endmodul { get; set; }
        public string Strxsrc { get; set; }
        public string Entrxsrc { get; set; }
        public string Stbchsrc { get; set; }
        public string Enbchsrc { get; set; }
        public string Stbchnum { get; set; }
        public string Endbnmbr { get; set; }
        public string Stvndrid { get; set; }
        public string Endvndid { get; set; }
        public byte Inqtyreq { get; set; }
        public byte Inzrorlv { get; set; }
        public short Calsgqty { get; set; }
        public short Rcptopts { get; set; }
        public short Vendropt { get; set; }
        public short Segsrtby { get; set; }
        public short Segmntrg { get; set; }
        public string StartPriceLevel { get; set; }
        public string EndPriceLevel { get; set; }
        public string StartRmaNumber { get; set; }
        public string EndRmaNumber { get; set; }
        public DateTime StartRequiredDate { get; set; }
        public DateTime EndRequiredDate { get; set; }
        public byte SvcPrintOpen { get; set; }
        public byte Incmcinf { get; set; }
        public short Prtcurin { get; set; }
        public int DexRowId { get; set; }
    }
}
