using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Sy70501
    {
        public short Origingb { get; set; }
        public short Strtyear { get; set; }
        public short Endyear { get; set; }
        public string Sticid { get; set; }
        public string Endicid { get; set; }
        public string Finrptnm { get; set; }
        public byte Sjrntprt { get; set; }
        public byte Prntnots { get; set; }
        public short Prnttype { get; set; }
        public byte Askechtm { get; set; }
        public byte Prntofil { get; set; }
        public byte Prtoprtr { get; set; }
        public byte Prtoscrn { get; set; }
        public byte Inclgnds { get; set; }
        public short Iffilxst { get; set; }
        public string Filexpnm { get; set; }
        public short Expttype { get; set; }
        public short Rptgrind { get; set; }
        public short Rtpachin { get; set; }
        public decimal Rtgrsbin { get; set; }
        public short Sortby { get; set; }
        public string Sttlocid { get; set; }
        public string Sttlocnm { get; set; }
        public string Staddctt { get; set; }
        public string Ssrcedoc { get; set; }
        public string Ssdocdsc { get; set; }
        public string Sttstate { get; set; }
        public string Strtzpcd { get; set; }
        public short Sttflsrs { get; set; }
        public short Startsrs { get; set; }
        public string Sttrxsrc { get; set; }
        public string Sttnotnm { get; set; }
        public string Srptgrnm { get; set; }
        public string Sttpalnm { get; set; }
        public string Sttusrid { get; set; }
        public short Stendtyp { get; set; }
        public string Sttcrdnm { get; set; }
        public string Sttpytid { get; set; }
        public string Sttshmth { get; set; }
        public short Srtcomsr { get; set; }
        public string Srtcomid { get; set; }
        public string Endlocid { get; set; }
        public string Endlocnm { get; set; }
        public string Endaddct { get; set; }
        public string Endsrcdc { get; set; }
        public string Endsddsc { get; set; }
        public string Endstate { get; set; }
        public string Endzipcd { get; set; }
        public short Endflsrs { get; set; }
        public short Endseris { get; set; }
        public string Endtrxsr { get; set; }
        public string Endnotnm { get; set; }
        public string Endrpgnm { get; set; }
        public string Endpalnm { get; set; }
        public string Endusrid { get; set; }
        public short Endendty { get; set; }
        public string Endcrdnm { get; set; }
        public string Endpytid { get; set; }
        public string Endshmth { get; set; }
        public string Endcomid { get; set; }
        public short Endcomsr { get; set; }
        public string Endname { get; set; }
        public string Endid { get; set; }
        public string Startid { get; set; }
        public string Strtname { get; set; }
        public string Strtcity { get; set; }
        public string Endcity { get; set; }
        public string Endcntry { get; set; }
        public string Sttcntry { get; set; }
        public short Lblfrmat { get; set; }
        public short Numocpis { get; set; }
        public short Numacros { get; set; }
        public byte Incadadr { get; set; }
        public byte Inccntct { get; set; }
        public byte Frceupcs { get; set; }
        public short Year1 { get; set; }
        public byte Prntdtld { get; set; }
        public string Entxddsc { get; set; }
        public string Etxdtlid { get; set; }
        public string Etxschds { get; set; }
        public string Etxschid { get; set; }
        public string Sttxddsc { get; set; }
        public string Sttxdtid { get; set; }
        public string Stxscdsc { get; set; }
        public string Stxschid { get; set; }
        public short Endperod { get; set; }
        public short Stperiod { get; set; }
        public short Stdtltyp { get; set; }
        public short Endettyp { get; set; }
        public string Stxidnum { get; set; }
        public string Etxidnbr { get; set; }
        public short Histtype { get; set; }
        public string Stbchnum { get; set; }
        public DateTime Strtdate { get; set; }
        public string Stdocnum { get; set; }
        public string Endbnmbr { get; set; }
        public string Endocnum { get; set; }
        public DateTime Enddate { get; set; }
        public byte Prnshpto { get; set; }
        public byte Prtbllto { get; set; }
        public short Arvldepart { get; set; }
        public string Stcustid { get; set; }
        public string Encustid { get; set; }
        public short Stsoptyp { get; set; }
        public short Edsoptyp { get; set; }
        public string Upsidnbr { get; set; }
        public DateTime Sttdocdt { get; set; }
        public DateTime Enddocdt { get; set; }
        public short Stdoctyp { get; set; }
        public short Endoctyp { get; set; }
        public string Stvndrid { get; set; }
        public string Endvndid { get; set; }
        public short Strmtkdt { get; set; }
        public short Enrmtkdt { get; set; }
        public string Sttxusr1 { get; set; }
        public string Entxusr1 { get; set; }
        public short Sttokndt { get; set; }
        public short Endtkndt { get; set; }
        public DateTime Sttxpydt { get; set; }
        public DateTime Entxpydt { get; set; }
        public DateTime Sttpstdt { get; set; }
        public DateTime Endpstdt { get; set; }
        public short Stgenint1 { get; set; }
        public string Stdeclid { get; set; }
        public string Enddeclid { get; set; }
        public string Stintrsttrtrnid { get; set; }
        public string Endintrsttrtrnid { get; set; }
        public string Sttcc { get; set; }
        public string Endtcc { get; set; }
        public string Sttxrgnnum { get; set; }
        public string Endtxrgnnum { get; set; }
        public decimal Strtamnt { get; set; }
        public decimal Endamnt { get; set; }
        public short Groupbox { get; set; }
        public short Groupbx2 { get; set; }
        public byte Exclvoid { get; set; }
        public byte Prntcsv { get; set; }
        public int DexRowId { get; set; }
    }
}
