using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Upr00900
    {
        public string Employid { get; set; }
        public string Lpchknum { get; set; }
        public DateTime Lstpckdt { get; set; }
        public decimal Lpchkamt { get; set; }
        public decimal Groswags1 { get; set; }
        public decimal Groswags2 { get; set; }
        public decimal Groswags3 { get; set; }
        public decimal Groswags4 { get; set; }
        public decimal Groswags5 { get; set; }
        public decimal Groswags6 { get; set; }
        public decimal Groswags7 { get; set; }
        public decimal Groswags8 { get; set; }
        public decimal Groswags9 { get; set; }
        public decimal Groswags10 { get; set; }
        public decimal Groswags11 { get; set; }
        public decimal Groswags12 { get; set; }
        public decimal Fdwthldg1 { get; set; }
        public decimal Fdwthldg2 { get; set; }
        public decimal Fdwthldg3 { get; set; }
        public decimal Fdwthldg4 { get; set; }
        public decimal Fdwthldg5 { get; set; }
        public decimal Fdwthldg6 { get; set; }
        public decimal Fdwthldg7 { get; set; }
        public decimal Fdwthldg8 { get; set; }
        public decimal Fdwthldg9 { get; set; }
        public decimal Fdwthldg10 { get; set; }
        public decimal Fdwthldg11 { get; set; }
        public decimal Fdwthldg12 { get; set; }
        public decimal Ficasswg1 { get; set; }
        public decimal Ficasswg2 { get; set; }
        public decimal Ficasswg3 { get; set; }
        public decimal Ficasswg4 { get; set; }
        public decimal Ficasswg5 { get; set; }
        public decimal Ficasswg6 { get; set; }
        public decimal Ficasswg7 { get; set; }
        public decimal Ficasswg8 { get; set; }
        public decimal Ficasswg9 { get; set; }
        public decimal Ficasswg10 { get; set; }
        public decimal Ficasswg11 { get; set; }
        public decimal Ficasswg12 { get; set; }
        public decimal Ficamwgs1 { get; set; }
        public decimal Ficamwgs2 { get; set; }
        public decimal Ficamwgs3 { get; set; }
        public decimal Ficamwgs4 { get; set; }
        public decimal Ficamwgs5 { get; set; }
        public decimal Ficamwgs6 { get; set; }
        public decimal Ficamwgs7 { get; set; }
        public decimal Ficamwgs8 { get; set; }
        public decimal Ficamwgs9 { get; set; }
        public decimal Ficamwgs10 { get; set; }
        public decimal Ficamwgs11 { get; set; }
        public decimal Ficamwgs12 { get; set; }
        public decimal Ficasswh1 { get; set; }
        public decimal Ficasswh2 { get; set; }
        public decimal Ficasswh3 { get; set; }
        public decimal Ficasswh4 { get; set; }
        public decimal Ficasswh5 { get; set; }
        public decimal Ficasswh6 { get; set; }
        public decimal Ficasswh7 { get; set; }
        public decimal Ficasswh8 { get; set; }
        public decimal Ficasswh9 { get; set; }
        public decimal Ficasswh10 { get; set; }
        public decimal Ficasswh11 { get; set; }
        public decimal Ficasswh12 { get; set; }
        public decimal Ficamwdg1 { get; set; }
        public decimal Ficamwdg2 { get; set; }
        public decimal Ficamwdg3 { get; set; }
        public decimal Ficamwdg4 { get; set; }
        public decimal Ficamwdg5 { get; set; }
        public decimal Ficamwdg6 { get; set; }
        public decimal Ficamwdg7 { get; set; }
        public decimal Ficamwdg8 { get; set; }
        public decimal Ficamwdg9 { get; set; }
        public decimal Ficamwdg10 { get; set; }
        public decimal Ficamwdg11 { get; set; }
        public decimal Ficamwdg12 { get; set; }
        public decimal Sutawags1 { get; set; }
        public decimal Sutawags2 { get; set; }
        public decimal Sutawags3 { get; set; }
        public decimal Sutawags4 { get; set; }
        public decimal Sutawags5 { get; set; }
        public decimal Sutawags6 { get; set; }
        public decimal Sutawags7 { get; set; }
        public decimal Sutawags8 { get; set; }
        public decimal Sutawags9 { get; set; }
        public decimal Sutawags10 { get; set; }
        public decimal Sutawags11 { get; set; }
        public decimal Sutawags12 { get; set; }
        public decimal Futawags1 { get; set; }
        public decimal Futawags2 { get; set; }
        public decimal Futawags3 { get; set; }
        public decimal Futawags4 { get; set; }
        public decimal Futawags5 { get; set; }
        public decimal Futawags6 { get; set; }
        public decimal Futawags7 { get; set; }
        public decimal Futawags8 { get; set; }
        public decimal Futawags9 { get; set; }
        public decimal Futawags10 { get; set; }
        public decimal Futawags11 { get; set; }
        public decimal Futawags12 { get; set; }
        public decimal Netwages1 { get; set; }
        public decimal Netwages2 { get; set; }
        public decimal Netwages3 { get; set; }
        public decimal Netwages4 { get; set; }
        public decimal Netwages5 { get; set; }
        public decimal Netwages6 { get; set; }
        public decimal Netwages7 { get; set; }
        public decimal Netwages8 { get; set; }
        public decimal Netwages9 { get; set; }
        public decimal Netwages10 { get; set; }
        public decimal Netwages11 { get; set; }
        public decimal Netwages12 { get; set; }
        public short Year1 { get; set; }
        public decimal FederalWages1 { get; set; }
        public decimal FederalWages2 { get; set; }
        public decimal FederalWages3 { get; set; }
        public decimal FederalWages4 { get; set; }
        public decimal FederalWages5 { get; set; }
        public decimal FederalWages6 { get; set; }
        public decimal FederalWages7 { get; set; }
        public decimal FederalWages8 { get; set; }
        public decimal FederalWages9 { get; set; }
        public decimal FederalWages10 { get; set; }
        public decimal FederalWages11 { get; set; }
        public decimal FederalWages12 { get; set; }
        public int DexRowId { get; set; }
    }
}
