using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Upr00901
    {
        public string Employid { get; set; }
        public decimal ReportedTips121 { get; set; }
        public decimal ReportedTips122 { get; set; }
        public decimal ReportedTips123 { get; set; }
        public decimal ReportedTips124 { get; set; }
        public decimal ReportedTips125 { get; set; }
        public decimal ReportedTips126 { get; set; }
        public decimal ReportedTips127 { get; set; }
        public decimal ReportedTips128 { get; set; }
        public decimal ReportedTips129 { get; set; }
        public decimal ReportedTips1210 { get; set; }
        public decimal ReportedTips1211 { get; set; }
        public decimal ReportedTips1212 { get; set; }
        public decimal ChargedTips121 { get; set; }
        public decimal ChargedTips122 { get; set; }
        public decimal ChargedTips123 { get; set; }
        public decimal ChargedTips124 { get; set; }
        public decimal ChargedTips125 { get; set; }
        public decimal ChargedTips126 { get; set; }
        public decimal ChargedTips127 { get; set; }
        public decimal ChargedTips128 { get; set; }
        public decimal ChargedTips129 { get; set; }
        public decimal ChargedTips1210 { get; set; }
        public decimal ChargedTips1211 { get; set; }
        public decimal ChargedTips1212 { get; set; }
        public decimal FederalTaxOnTips1 { get; set; }
        public decimal FederalTaxOnTips2 { get; set; }
        public decimal FederalTaxOnTips3 { get; set; }
        public decimal FederalTaxOnTips4 { get; set; }
        public decimal FederalTaxOnTips5 { get; set; }
        public decimal FederalTaxOnTips6 { get; set; }
        public decimal FederalTaxOnTips7 { get; set; }
        public decimal FederalTaxOnTips8 { get; set; }
        public decimal FederalTaxOnTips9 { get; set; }
        public decimal FederalTaxOnTips10 { get; set; }
        public decimal FederalTaxOnTips11 { get; set; }
        public decimal FederalTaxOnTips12 { get; set; }
        public decimal FicassTips1 { get; set; }
        public decimal FicassTips2 { get; set; }
        public decimal FicassTips3 { get; set; }
        public decimal FicassTips4 { get; set; }
        public decimal FicassTips5 { get; set; }
        public decimal FicassTips6 { get; set; }
        public decimal FicassTips7 { get; set; }
        public decimal FicassTips8 { get; set; }
        public decimal FicassTips9 { get; set; }
        public decimal FicassTips10 { get; set; }
        public decimal FicassTips11 { get; set; }
        public decimal FicassTips12 { get; set; }
        public decimal FicassTaxOnTips1 { get; set; }
        public decimal FicassTaxOnTips2 { get; set; }
        public decimal FicassTaxOnTips3 { get; set; }
        public decimal FicassTaxOnTips4 { get; set; }
        public decimal FicassTaxOnTips5 { get; set; }
        public decimal FicassTaxOnTips6 { get; set; }
        public decimal FicassTaxOnTips7 { get; set; }
        public decimal FicassTaxOnTips8 { get; set; }
        public decimal FicassTaxOnTips9 { get; set; }
        public decimal FicassTaxOnTips10 { get; set; }
        public decimal FicassTaxOnTips11 { get; set; }
        public decimal FicassTaxOnTips12 { get; set; }
        public decimal UncollectedFicassTax1 { get; set; }
        public decimal UncollectedFicassTax2 { get; set; }
        public decimal UncollectedFicassTax3 { get; set; }
        public decimal UncollectedFicassTax4 { get; set; }
        public decimal UncollectedFicassTax5 { get; set; }
        public decimal UncollectedFicassTax6 { get; set; }
        public decimal UncollectedFicassTax7 { get; set; }
        public decimal UncollectedFicassTax8 { get; set; }
        public decimal UncollectedFicassTax9 { get; set; }
        public decimal UncollectedFicassTax10 { get; set; }
        public decimal UncollectedFicassTax11 { get; set; }
        public decimal UncollectedFicassTax12 { get; set; }
        public decimal FicamedTips1 { get; set; }
        public decimal FicamedTips2 { get; set; }
        public decimal FicamedTips3 { get; set; }
        public decimal FicamedTips4 { get; set; }
        public decimal FicamedTips5 { get; set; }
        public decimal FicamedTips6 { get; set; }
        public decimal FicamedTips7 { get; set; }
        public decimal FicamedTips8 { get; set; }
        public decimal FicamedTips9 { get; set; }
        public decimal FicamedTips10 { get; set; }
        public decimal FicamedTips11 { get; set; }
        public decimal FicamedTips12 { get; set; }
        public decimal FicamedTaxOnTips1 { get; set; }
        public decimal FicamedTaxOnTips2 { get; set; }
        public decimal FicamedTaxOnTips3 { get; set; }
        public decimal FicamedTaxOnTips4 { get; set; }
        public decimal FicamedTaxOnTips5 { get; set; }
        public decimal FicamedTaxOnTips6 { get; set; }
        public decimal FicamedTaxOnTips7 { get; set; }
        public decimal FicamedTaxOnTips8 { get; set; }
        public decimal FicamedTaxOnTips9 { get; set; }
        public decimal FicamedTaxOnTips10 { get; set; }
        public decimal FicamedTaxOnTips11 { get; set; }
        public decimal FicamedTaxOnTips12 { get; set; }
        public decimal UncollectedFicamedTax1 { get; set; }
        public decimal UncollectedFicamedTax2 { get; set; }
        public decimal UncollectedFicamedTax3 { get; set; }
        public decimal UncollectedFicamedTax4 { get; set; }
        public decimal UncollectedFicamedTax5 { get; set; }
        public decimal UncollectedFicamedTax6 { get; set; }
        public decimal UncollectedFicamedTax7 { get; set; }
        public decimal UncollectedFicamedTax8 { get; set; }
        public decimal UncollectedFicamedTax9 { get; set; }
        public decimal UncollectedFicamedTax10 { get; set; }
        public decimal UncollectedFicamedTax11 { get; set; }
        public decimal UncollectedFicamedTax12 { get; set; }
        public decimal ReportedReceipts121 { get; set; }
        public decimal ReportedReceipts122 { get; set; }
        public decimal ReportedReceipts123 { get; set; }
        public decimal ReportedReceipts124 { get; set; }
        public decimal ReportedReceipts125 { get; set; }
        public decimal ReportedReceipts126 { get; set; }
        public decimal ReportedReceipts127 { get; set; }
        public decimal ReportedReceipts128 { get; set; }
        public decimal ReportedReceipts129 { get; set; }
        public decimal ReportedReceipts1210 { get; set; }
        public decimal ReportedReceipts1211 { get; set; }
        public decimal ReportedReceipts1212 { get; set; }
        public decimal ChargedReceipts121 { get; set; }
        public decimal ChargedReceipts122 { get; set; }
        public decimal ChargedReceipts123 { get; set; }
        public decimal ChargedReceipts124 { get; set; }
        public decimal ChargedReceipts125 { get; set; }
        public decimal ChargedReceipts126 { get; set; }
        public decimal ChargedReceipts127 { get; set; }
        public decimal ChargedReceipts128 { get; set; }
        public decimal ChargedReceipts129 { get; set; }
        public decimal ChargedReceipts1210 { get; set; }
        public decimal ChargedReceipts1211 { get; set; }
        public decimal ChargedReceipts1212 { get; set; }
        public decimal AllocatedTipsArray1 { get; set; }
        public decimal AllocatedTipsArray2 { get; set; }
        public decimal AllocatedTipsArray3 { get; set; }
        public decimal AllocatedTipsArray4 { get; set; }
        public decimal AllocatedTipsArray5 { get; set; }
        public decimal AllocatedTipsArray6 { get; set; }
        public decimal AllocatedTipsArray7 { get; set; }
        public decimal AllocatedTipsArray8 { get; set; }
        public decimal AllocatedTipsArray9 { get; set; }
        public decimal AllocatedTipsArray10 { get; set; }
        public decimal AllocatedTipsArray11 { get; set; }
        public decimal AllocatedTipsArray12 { get; set; }
        public short Year1 { get; set; }
        public decimal FederalTips1 { get; set; }
        public decimal FederalTips2 { get; set; }
        public decimal FederalTips3 { get; set; }
        public decimal FederalTips4 { get; set; }
        public decimal FederalTips5 { get; set; }
        public decimal FederalTips6 { get; set; }
        public decimal FederalTips7 { get; set; }
        public decimal FederalTips8 { get; set; }
        public decimal FederalTips9 { get; set; }
        public decimal FederalTips10 { get; set; }
        public decimal FederalTips11 { get; set; }
        public decimal FederalTips12 { get; set; }
        public int DexRowId { get; set; }
    }
}
