using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Upr10213
    {
        public string Employid { get; set; }
        public string Pycddsar1 { get; set; }
        public string Pycddsar2 { get; set; }
        public string Pycddsar3 { get; set; }
        public string Pycddsar4 { get; set; }
        public string Pycddsar5 { get; set; }
        public string Pycddsar6 { get; set; }
        public string Pycddsar7 { get; set; }
        public string Pycddsar8 { get; set; }
        public string Pycddsar9 { get; set; }
        public string Pycddsar10 { get; set; }
        public string Pycddsar11 { get; set; }
        public string Pycddsar12 { get; set; }
        public string Pycddsar13 { get; set; }
        public string Pycddsar14 { get; set; }
        public string Pycddsar15 { get; set; }
        public string Pycddsar16 { get; set; }
        public string Pycddsar17 { get; set; }
        public string Pycddsar18 { get; set; }
        public string Pycddsar19 { get; set; }
        public string Pycddsar20 { get; set; }
        public string Pycddsar21 { get; set; }
        public string Pycddsar22 { get; set; }
        public string Pycddsar23 { get; set; }
        public string Pycddsar24 { get; set; }
        public string Pycddsar25 { get; set; }
        public string Deddesar1 { get; set; }
        public string Deddesar2 { get; set; }
        public string Deddesar3 { get; set; }
        public string Deddesar4 { get; set; }
        public string Deddesar5 { get; set; }
        public string Deddesar6 { get; set; }
        public string Deddesar7 { get; set; }
        public string Deddesar8 { get; set; }
        public string Deddesar9 { get; set; }
        public string Deddesar10 { get; set; }
        public string Deddesar11 { get; set; }
        public string Deddesar12 { get; set; }
        public string Deddesar13 { get; set; }
        public string Deddesar14 { get; set; }
        public string Deddesar15 { get; set; }
        public string Deddesar16 { get; set; }
        public string Deddesar17 { get; set; }
        public string Deddesar18 { get; set; }
        public string Deddesar19 { get; set; }
        public string Deddesar20 { get; set; }
        public string Deddesar21 { get; set; }
        public string Deddesar22 { get; set; }
        public string Deddesar23 { get; set; }
        public string Deddesar24 { get; set; }
        public string Deddesar25 { get; set; }
        public string Bendesar1 { get; set; }
        public string Bendesar2 { get; set; }
        public string Bendesar3 { get; set; }
        public string Bendesar4 { get; set; }
        public string Bendesar5 { get; set; }
        public string Bendesar6 { get; set; }
        public string Bendesar7 { get; set; }
        public string Bendesar8 { get; set; }
        public string Bendesar9 { get; set; }
        public string Bendesar10 { get; set; }
        public string Bendesar11 { get; set; }
        public string Bendesar12 { get; set; }
        public string Bendesar13 { get; set; }
        public string Bendesar14 { get; set; }
        public string Bendesar15 { get; set; }
        public string Bendesar16 { get; set; }
        public string Bendesar17 { get; set; }
        public string Bendesar18 { get; set; }
        public string Bendesar19 { get; set; }
        public string Bendesar20 { get; set; }
        public string Bendesar21 { get; set; }
        public string Bendesar22 { get; set; }
        public string Bendesar23 { get; set; }
        public string Bendesar24 { get; set; }
        public string Bendesar25 { get; set; }
        public string Timecodedescarray1 { get; set; }
        public string Timecodedescarray2 { get; set; }
        public string Timecodedescarray3 { get; set; }
        public string Timecodedescarray4 { get; set; }
        public string Timecodedescarray5 { get; set; }
        public string Timecodedescarray6 { get; set; }
        public string Timecodedescarray7 { get; set; }
        public string Timecodedescarray8 { get; set; }
        public string Timecodedescarray9 { get; set; }
        public string Timecodedescarray10 { get; set; }
        public string Timecodedescarray11 { get; set; }
        public string Timecodedescarray12 { get; set; }
        public string Timecodedescarray13 { get; set; }
        public string Timecodedescarray14 { get; set; }
        public string Timecodedescarray15 { get; set; }
        public string Timecodedescarray16 { get; set; }
        public string Timecodedescarray17 { get; set; }
        public string Timecodedescarray18 { get; set; }
        public string Timecodedescarray19 { get; set; }
        public string Timecodedescarray20 { get; set; }
        public string Timecodedescarray21 { get; set; }
        public string Timecodedescarray22 { get; set; }
        public string Timecodedescarray23 { get; set; }
        public string Timecodedescarray24 { get; set; }
        public string Timecodedescarray25 { get; set; }
        public string Payarrcd1 { get; set; }
        public string Payarrcd2 { get; set; }
        public string Payarrcd3 { get; set; }
        public string Payarrcd4 { get; set; }
        public string Payarrcd5 { get; set; }
        public string Payarrcd6 { get; set; }
        public string Payarrcd7 { get; set; }
        public string Payarrcd8 { get; set; }
        public string Payarrcd9 { get; set; }
        public string Payarrcd10 { get; set; }
        public string Payarrcd11 { get; set; }
        public string Payarrcd12 { get; set; }
        public string Payarrcd13 { get; set; }
        public string Payarrcd14 { get; set; }
        public string Payarrcd15 { get; set; }
        public string Payarrcd16 { get; set; }
        public string Payarrcd17 { get; set; }
        public string Payarrcd18 { get; set; }
        public string Payarrcd19 { get; set; }
        public string Payarrcd20 { get; set; }
        public string Payarrcd21 { get; set; }
        public string Payarrcd22 { get; set; }
        public string Payarrcd23 { get; set; }
        public string Payarrcd24 { get; set; }
        public string Payarrcd25 { get; set; }
        public string Dedcdarr1 { get; set; }
        public string Dedcdarr2 { get; set; }
        public string Dedcdarr3 { get; set; }
        public string Dedcdarr4 { get; set; }
        public string Dedcdarr5 { get; set; }
        public string Dedcdarr6 { get; set; }
        public string Dedcdarr7 { get; set; }
        public string Dedcdarr8 { get; set; }
        public string Dedcdarr9 { get; set; }
        public string Dedcdarr10 { get; set; }
        public string Dedcdarr11 { get; set; }
        public string Dedcdarr12 { get; set; }
        public string Dedcdarr13 { get; set; }
        public string Dedcdarr14 { get; set; }
        public string Dedcdarr15 { get; set; }
        public string Dedcdarr16 { get; set; }
        public string Dedcdarr17 { get; set; }
        public string Dedcdarr18 { get; set; }
        public string Dedcdarr19 { get; set; }
        public string Dedcdarr20 { get; set; }
        public string Dedcdarr21 { get; set; }
        public string Dedcdarr22 { get; set; }
        public string Dedcdarr23 { get; set; }
        public string Dedcdarr24 { get; set; }
        public string Dedcdarr25 { get; set; }
        public string Bnfcdarr1 { get; set; }
        public string Bnfcdarr2 { get; set; }
        public string Bnfcdarr3 { get; set; }
        public string Bnfcdarr4 { get; set; }
        public string Bnfcdarr5 { get; set; }
        public string Bnfcdarr6 { get; set; }
        public string Bnfcdarr7 { get; set; }
        public string Bnfcdarr8 { get; set; }
        public string Bnfcdarr9 { get; set; }
        public string Bnfcdarr10 { get; set; }
        public string Bnfcdarr11 { get; set; }
        public string Bnfcdarr12 { get; set; }
        public string Bnfcdarr13 { get; set; }
        public string Bnfcdarr14 { get; set; }
        public string Bnfcdarr15 { get; set; }
        public string Bnfcdarr16 { get; set; }
        public string Bnfcdarr17 { get; set; }
        public string Bnfcdarr18 { get; set; }
        public string Bnfcdarr19 { get; set; }
        public string Bnfcdarr20 { get; set; }
        public string Bnfcdarr21 { get; set; }
        public string Bnfcdarr22 { get; set; }
        public string Bnfcdarr23 { get; set; }
        public string Bnfcdarr24 { get; set; }
        public string Bnfcdarr25 { get; set; }
        public string Timecodearray1 { get; set; }
        public string Timecodearray2 { get; set; }
        public string Timecodearray3 { get; set; }
        public string Timecodearray4 { get; set; }
        public string Timecodearray5 { get; set; }
        public string Timecodearray6 { get; set; }
        public string Timecodearray7 { get; set; }
        public string Timecodearray8 { get; set; }
        public string Timecodearray9 { get; set; }
        public string Timecodearray10 { get; set; }
        public string Timecodearray11 { get; set; }
        public string Timecodearray12 { get; set; }
        public string Timecodearray13 { get; set; }
        public string Timecodearray14 { get; set; }
        public string Timecodearray15 { get; set; }
        public string Timecodearray16 { get; set; }
        public string Timecodearray17 { get; set; }
        public string Timecodearray18 { get; set; }
        public string Timecodearray19 { get; set; }
        public string Timecodearray20 { get; set; }
        public string Timecodearray21 { get; set; }
        public string Timecodearray22 { get; set; }
        public string Timecodearray23 { get; set; }
        public string Timecodearray24 { get; set; }
        public string Timecodearray25 { get; set; }
        public string Statxarr1 { get; set; }
        public string Statxarr2 { get; set; }
        public string Statxarr3 { get; set; }
        public string Statxarr4 { get; set; }
        public string Statxarr5 { get; set; }
        public string Statxarr6 { get; set; }
        public string Statxarr7 { get; set; }
        public string Statxarr8 { get; set; }
        public string Statxarr9 { get; set; }
        public string Statxarr10 { get; set; }
        public string Statxarr11 { get; set; }
        public string Statxarr12 { get; set; }
        public string Statxarr13 { get; set; }
        public string Statxarr14 { get; set; }
        public string Statxarr15 { get; set; }
        public string Statxarr16 { get; set; }
        public string Statxarr17 { get; set; }
        public string Statxarr18 { get; set; }
        public string Statxarr19 { get; set; }
        public string Statxarr20 { get; set; }
        public string Statxarr21 { get; set; }
        public string Statxarr22 { get; set; }
        public string Statxarr23 { get; set; }
        public string Statxarr24 { get; set; }
        public string Statxarr25 { get; set; }
        public string Lcltxarr1 { get; set; }
        public string Lcltxarr2 { get; set; }
        public string Lcltxarr3 { get; set; }
        public string Lcltxarr4 { get; set; }
        public string Lcltxarr5 { get; set; }
        public string Lcltxarr6 { get; set; }
        public string Lcltxarr7 { get; set; }
        public string Lcltxarr8 { get; set; }
        public string Lcltxarr9 { get; set; }
        public string Lcltxarr10 { get; set; }
        public string Lcltxarr11 { get; set; }
        public string Lcltxarr12 { get; set; }
        public string Lcltxarr13 { get; set; }
        public string Lcltxarr14 { get; set; }
        public string Lcltxarr15 { get; set; }
        public string Lcltxarr16 { get; set; }
        public string Lcltxarr17 { get; set; }
        public string Lcltxarr18 { get; set; }
        public string Lcltxarr19 { get; set; }
        public string Lcltxarr20 { get; set; }
        public string Lcltxarr21 { get; set; }
        public string Lcltxarr22 { get; set; }
        public string Lcltxarr23 { get; set; }
        public string Lcltxarr24 { get; set; }
        public string Lcltxarr25 { get; set; }
        public string Userid { get; set; }
        public int DexRowId { get; set; }
    }
}
