using System;
using System.Collections.Generic;

namespace DynamicsGPAPI.Models
{
    public partial class Upr10208
    {
        public byte Printed { get; set; }
        public byte Voided { get; set; }
        public string Userid { get; set; }
        public string Employid { get; set; }
        public string Emplname { get; set; }
        public string Lastname { get; set; }
        public string Frstname { get; set; }
        public string Midlname { get; set; }
        public DateTime Chekdate { get; set; }
        public string Cheknmbr { get; set; }
        public int Pyadnmbr { get; set; }
        public string Deprtmnt { get; set; }
        public string Emplclas { get; set; }
        public string Socscnum { get; set; }
        public decimal Payrtarr1 { get; set; }
        public decimal Payrtarr2 { get; set; }
        public decimal Payrtarr3 { get; set; }
        public decimal Payrtarr4 { get; set; }
        public decimal Payrtarr5 { get; set; }
        public decimal Payrtarr6 { get; set; }
        public decimal Payrtarr7 { get; set; }
        public decimal Payrtarr8 { get; set; }
        public decimal Payrtarr9 { get; set; }
        public decimal Payrtarr10 { get; set; }
        public decimal Payrtarr11 { get; set; }
        public decimal Payrtarr12 { get; set; }
        public decimal Payrtarr13 { get; set; }
        public decimal Payrtarr14 { get; set; }
        public decimal Payrtarr15 { get; set; }
        public decimal Payrtarr16 { get; set; }
        public decimal Payrtarr17 { get; set; }
        public decimal Payrtarr18 { get; set; }
        public decimal Payrtarr19 { get; set; }
        public decimal Payrtarr20 { get; set; }
        public decimal Payrtarr21 { get; set; }
        public decimal Payrtarr22 { get; set; }
        public decimal Payrtarr23 { get; set; }
        public decimal Payrtarr24 { get; set; }
        public decimal Payrtarr25 { get; set; }
        public int Payhrsar1 { get; set; }
        public int Payhrsar2 { get; set; }
        public int Payhrsar3 { get; set; }
        public int Payhrsar4 { get; set; }
        public int Payhrsar5 { get; set; }
        public int Payhrsar6 { get; set; }
        public int Payhrsar7 { get; set; }
        public int Payhrsar8 { get; set; }
        public int Payhrsar9 { get; set; }
        public int Payhrsar10 { get; set; }
        public int Payhrsar11 { get; set; }
        public int Payhrsar12 { get; set; }
        public int Payhrsar13 { get; set; }
        public int Payhrsar14 { get; set; }
        public int Payhrsar15 { get; set; }
        public int Payhrsar16 { get; set; }
        public int Payhrsar17 { get; set; }
        public int Payhrsar18 { get; set; }
        public int Payhrsar19 { get; set; }
        public int Payhrsar20 { get; set; }
        public int Payhrsar21 { get; set; }
        public int Payhrsar22 { get; set; }
        public int Payhrsar23 { get; set; }
        public int Payhrsar24 { get; set; }
        public int Payhrsar25 { get; set; }
        public decimal Payernar1 { get; set; }
        public decimal Payernar2 { get; set; }
        public decimal Payernar3 { get; set; }
        public decimal Payernar4 { get; set; }
        public decimal Payernar5 { get; set; }
        public decimal Payernar6 { get; set; }
        public decimal Payernar7 { get; set; }
        public decimal Payernar8 { get; set; }
        public decimal Payernar9 { get; set; }
        public decimal Payernar10 { get; set; }
        public decimal Payernar11 { get; set; }
        public decimal Payernar12 { get; set; }
        public decimal Payernar13 { get; set; }
        public decimal Payernar14 { get; set; }
        public decimal Payernar15 { get; set; }
        public decimal Payernar16 { get; set; }
        public decimal Payernar17 { get; set; }
        public decimal Payernar18 { get; set; }
        public decimal Payernar19 { get; set; }
        public decimal Payernar20 { get; set; }
        public decimal Payernar21 { get; set; }
        public decimal Payernar22 { get; set; }
        public decimal Payernar23 { get; set; }
        public decimal Payernar24 { get; set; }
        public decimal Payernar25 { get; set; }
        public decimal Tficatwh { get; set; }
        public decimal Fcaswpr { get; set; }
        public decimal Ficamwpr { get; set; }
        public decimal Fdwdgprn { get; set; }
        public decimal Stwhdarr1 { get; set; }
        public decimal Stwhdarr2 { get; set; }
        public decimal Stwhdarr3 { get; set; }
        public decimal Stwhdarr4 { get; set; }
        public decimal Stwhdarr5 { get; set; }
        public decimal Stwhdarr6 { get; set; }
        public decimal Stwhdarr7 { get; set; }
        public decimal Stwhdarr8 { get; set; }
        public decimal Stwhdarr9 { get; set; }
        public decimal Stwhdarr10 { get; set; }
        public decimal Stwhdarr11 { get; set; }
        public decimal Stwhdarr12 { get; set; }
        public decimal Stwhdarr13 { get; set; }
        public decimal Stwhdarr14 { get; set; }
        public decimal Stwhdarr15 { get; set; }
        public decimal Stwhdarr16 { get; set; }
        public decimal Stwhdarr17 { get; set; }
        public decimal Stwhdarr18 { get; set; }
        public decimal Stwhdarr19 { get; set; }
        public decimal Stwhdarr20 { get; set; }
        public decimal Stwhdarr21 { get; set; }
        public decimal Stwhdarr22 { get; set; }
        public decimal Stwhdarr23 { get; set; }
        public decimal Stwhdarr24 { get; set; }
        public decimal Stwhdarr25 { get; set; }
        public decimal Ltxwhgar1 { get; set; }
        public decimal Ltxwhgar2 { get; set; }
        public decimal Ltxwhgar3 { get; set; }
        public decimal Ltxwhgar4 { get; set; }
        public decimal Ltxwhgar5 { get; set; }
        public decimal Ltxwhgar6 { get; set; }
        public decimal Ltxwhgar7 { get; set; }
        public decimal Ltxwhgar8 { get; set; }
        public decimal Ltxwhgar9 { get; set; }
        public decimal Ltxwhgar10 { get; set; }
        public decimal Ltxwhgar11 { get; set; }
        public decimal Ltxwhgar12 { get; set; }
        public decimal Ltxwhgar13 { get; set; }
        public decimal Ltxwhgar14 { get; set; }
        public decimal Ltxwhgar15 { get; set; }
        public decimal Ltxwhgar16 { get; set; }
        public decimal Ltxwhgar17 { get; set; }
        public decimal Ltxwhgar18 { get; set; }
        public decimal Ltxwhgar19 { get; set; }
        public decimal Ltxwhgar20 { get; set; }
        public decimal Ltxwhgar21 { get; set; }
        public decimal Ltxwhgar22 { get; set; }
        public decimal Ltxwhgar23 { get; set; }
        public decimal Ltxwhgar24 { get; set; }
        public decimal Ltxwhgar25 { get; set; }
        public decimal Dedamarr1 { get; set; }
        public decimal Dedamarr2 { get; set; }
        public decimal Dedamarr3 { get; set; }
        public decimal Dedamarr4 { get; set; }
        public decimal Dedamarr5 { get; set; }
        public decimal Dedamarr6 { get; set; }
        public decimal Dedamarr7 { get; set; }
        public decimal Dedamarr8 { get; set; }
        public decimal Dedamarr9 { get; set; }
        public decimal Dedamarr10 { get; set; }
        public decimal Dedamarr11 { get; set; }
        public decimal Dedamarr12 { get; set; }
        public decimal Dedamarr13 { get; set; }
        public decimal Dedamarr14 { get; set; }
        public decimal Dedamarr15 { get; set; }
        public decimal Dedamarr16 { get; set; }
        public decimal Dedamarr17 { get; set; }
        public decimal Dedamarr18 { get; set; }
        public decimal Dedamarr19 { get; set; }
        public decimal Dedamarr20 { get; set; }
        public decimal Dedamarr21 { get; set; }
        public decimal Dedamarr22 { get; set; }
        public decimal Dedamarr23 { get; set; }
        public decimal Dedamarr24 { get; set; }
        public decimal Dedamarr25 { get; set; }
        public decimal Bnfamarr1 { get; set; }
        public decimal Bnfamarr2 { get; set; }
        public decimal Bnfamarr3 { get; set; }
        public decimal Bnfamarr4 { get; set; }
        public decimal Bnfamarr5 { get; set; }
        public decimal Bnfamarr6 { get; set; }
        public decimal Bnfamarr7 { get; set; }
        public decimal Bnfamarr8 { get; set; }
        public decimal Bnfamarr9 { get; set; }
        public decimal Bnfamarr10 { get; set; }
        public decimal Bnfamarr11 { get; set; }
        public decimal Bnfamarr12 { get; set; }
        public decimal Bnfamarr13 { get; set; }
        public decimal Bnfamarr14 { get; set; }
        public decimal Bnfamarr15 { get; set; }
        public decimal Bnfamarr16 { get; set; }
        public decimal Bnfamarr17 { get; set; }
        public decimal Bnfamarr18 { get; set; }
        public decimal Bnfamarr19 { get; set; }
        public decimal Bnfamarr20 { get; set; }
        public decimal Bnfamarr21 { get; set; }
        public decimal Bnfamarr22 { get; set; }
        public decimal Bnfamarr23 { get; set; }
        public decimal Bnfamarr24 { get; set; }
        public decimal Bnfamarr25 { get; set; }
        public decimal Timeavailarray1 { get; set; }
        public decimal Timeavailarray2 { get; set; }
        public decimal Timeavailarray3 { get; set; }
        public decimal Timeavailarray4 { get; set; }
        public decimal Timeavailarray5 { get; set; }
        public decimal Timeavailarray6 { get; set; }
        public decimal Timeavailarray7 { get; set; }
        public decimal Timeavailarray8 { get; set; }
        public decimal Timeavailarray9 { get; set; }
        public decimal Timeavailarray10 { get; set; }
        public decimal Timeavailarray11 { get; set; }
        public decimal Timeavailarray12 { get; set; }
        public decimal Timeavailarray13 { get; set; }
        public decimal Timeavailarray14 { get; set; }
        public decimal Timeavailarray15 { get; set; }
        public decimal Timeavailarray16 { get; set; }
        public decimal Timeavailarray17 { get; set; }
        public decimal Timeavailarray18 { get; set; }
        public decimal Timeavailarray19 { get; set; }
        public decimal Timeavailarray20 { get; set; }
        public decimal Timeavailarray21 { get; set; }
        public decimal Timeavailarray22 { get; set; }
        public decimal Timeavailarray23 { get; set; }
        public decimal Timeavailarray24 { get; set; }
        public decimal Timeavailarray25 { get; set; }
        public int Ttlhours { get; set; }
        public decimal Ttlerngs { get; set; }
        public decimal Totltaxs { get; set; }
        public decimal Ttlddtns { get; set; }
        public decimal Ttlbnfts { get; set; }
        public decimal Ntwpyrn { get; set; }
        public decimal Grwgprn { get; set; }
        public int Reghours { get; set; }
        public decimal Regerngs { get; set; }
        public int Ovrtmhrs { get; set; }
        public decimal Ovtmearn { get; set; }
        public int Dbltmhrs { get; set; }
        public decimal Dbltmern { get; set; }
        public decimal Eicerngs { get; set; }
        public decimal Commerng { get; set; }
        public decimal Bsnexern { get; set; }
        public decimal Pnsnerng { get; set; }
        public int Holdyhrs { get; set; }
        public decimal Hldyearn { get; set; }
        public int Vactnhrs { get; set; }
        public decimal Vctnerng { get; set; }
        public int Sktimhrs { get; set; }
        public decimal Sktmerng { get; set; }
        public int Pcwkunit { get; set; }
        public decimal Pcwkerng { get; set; }
        public decimal Spclerng { get; set; }
        public decimal Chgtpern { get; set; }
        public decimal Reptpern { get; set; }
        public decimal Mnwgbler { get; set; }
        public int Vacavlbl { get; set; }
        public int Siktimav { get; set; }
        public DateTime Sttpyprd { get; set; }
        public DateTime Enpayprd { get; set; }
        public decimal UncollectedFicamedTaxP { get; set; }
        public decimal UncollectedFicassTaxP { get; set; }
        public string Rsnchkvd { get; set; }
        public int DexRowId { get; set; }
        public string Amtinwds { get; set; }
    }
}
